### ISSUE TITLE
PGO_FEATURE_GATES not work

### ISSUE THREAD

**Issue by todeb** [CrunchyData/postgres-operator#3592] opened 2023-03-03 08:35 UTC
Set env variable in pgo deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    meta.helm.sh/release-name: postgres-operator
    meta.helm.sh/release-namespace: postgres-operator
  creationTimestamp: "2022-05-16T10:22:43Z"
  generation: 4
  labels:
    app.kubernetes.io/instance: postgres-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: pgo
    app.kubernetes.io/version: 5.2.0
    helm.sh/chart: pgo-0.6.0
    postgres-operator.crunchydata.com/control-plane: pgo
  name: pgo
  namespace: postgres-operator
  resourceVersion: "129821418"
  uid: 45579bdf-d501-4af4-9f92-8e333423bfb9
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      postgres-operator.crunchydata.com/control-plane: pgo
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        postgres-operator.crunchydata.com/control-plane: pgo
    spec:
      containers:
      - env:
        - name: PGO_FEATURE_GATES
          value: PGBouncerSidecars=true
        - name: CRUNCHY_DEBUG
          value: "true"
        - name: PGO_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: RELATED_IMAGE_PGADMIN
          value: registry.developers.crunchydata.com/crunchydata/crunchy-pgadmin4:ubi8-4.30-4
        - name: RELATED_IMAGE_PGBACKREST
          value: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.40-1
        - name: RELATED_IMAGE_PGBOUNCER
          value: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:ubi8-1.17-1
        - name: RELATED_IMAGE_PGEXPORTER
          value: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.2.0-0
        - name: RELATED_IMAGE_PGUPGRADE
          value: registry.developers.crunchydata.com/crunchydata/crunchy-upgrade:ubi8-5.2.0-0
        - name: RELATED_IMAGE_POSTGRES_13
          value: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-13.8-1
        - name: RELATED_IMAGE_POSTGRES_13_GIS_3.0
          value: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis:ubi8-13.8-3.0-1
        - name: RELATED_IMAGE_POSTGRES_13_GIS_3.1
          value: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis:ubi8-13.8-3.1-1
        - name: RELATED_IMAGE_POSTGRES_14
          value: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.5-1
        - name: RELATED_IMAGE_POSTGRES_14_GIS_3.1
          value: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis:ubi8-14.5-3.1-1
        - name: RELATED_IMAGE_POSTGRES_14_GIS_3.2
          value: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis:ubi8-14.5-3.2-1
        image: registry.developers.crunchydata.com/crunchydata/postgres-operator:ubi8-5.2.0-0
        imagePullPolicy: IfNotPresent
        name: operator
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: pgo
      serviceAccountName: pgo
      terminationGracePeriodSeconds: 30
```

```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: pgsql-test
  namespace: database-services
spec:
  imagePullSecrets:
    - name: dcksecret
  image: mydck/crunchydata/crunchy-postgres:ubi8-13.8-1
  postgresVersion: 13
  users:
    - name: pgadmin
      options: "SUPERUSER"
    - name: appuser-test
      databases:
        - test
  instances:
    - name: pgha1
      containers:
      - name: test
        image: alpine:latest
      replicas: 1
      resources:
        limits:
          cpu: 2
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 1Gi
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gil
  backups:
    pgbackrest:
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi
  proxy:
    pgBouncer:
      replicas: 2
      config:
        global:
          pool_mode: transaction
          server_reset_query: DISCARD ALL
          application_name_add_host: "1"
          max_client_conn: "500"
          default_pool_size: "50"
```

Expected to have 5/5 containers. But having 4/4

pgsql-test-pgha1-lnlk-0                     4/4     Running     0             8s

**Comment by benjaminjb** [comment] 2023-03-03 14:58
I think the problem is that you're using the `PGBouncerSidecars` feature gate, but trying to create a custom sidecar in the postgres instance. I think this will work if you either

a) use the `InstanceSidecars` feature gate and use the cluster yaml you've given OR
b) put the containers in `spec.proxy.pgBouncer.containers` and use the PGO yaml you've given (with `PGBouncerSidecars` feature gate)

Ref: https://access.crunchydata.com/documentation/postgres-operator/5.3.1/tutorial/customize-cluster/#custom-sidecar-containers

If that doesn't work, please reopen this issue, but it just worked for me, so I'll close this now.

**Closed by benjaminjb** 2023-03-03 14:58 UTC
