### ISSUE TITLE
cannot connect via pgbouncer

### ISSUE THREAD

**Issue by shimon-elbaz** [CrunchyData/postgres-operator#3123] opened 2022-03-31 13:03 UTC
hi , 
i have setup an environment on GKE using the provided samples.

my general environment:
pgo , pgbouncer , ha-postgress.

whenever i try to use the bouncer , i fail to connect to the database , but when i connect to the postgres-ha service i have the access i need.

it seems that i simply need to edit my pgbouncer settings, but i am unable to do so.
whenever i try to edit the YAML directly , it is overwritten by the pgo.
when i added a new config-map containing my file - it was ignored.

as far as i understand , i need to edit the files:
- pgbouncer.ini
- pg_hba.conf

can anyone please assist?

**Comment by luber** [comment] 2022-05-05 21:35
I have the same issue.
```
  proxy:
    pgBouncer:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:ubi8-1.16-2
```

When I am trying to connect - this is what I see in logs:
```
2022-05-05 21:21:36.022 UTC [7] LOG kernel file descriptor limit: 1048576 (hard: 1048576); max_client_conn: 100, max expected fd use: 112
2022-05-05 21:21:36.022 UTC [7] LOG listening on 0.0.0.0:5432
2022-05-05 21:21:36.022 UTC [7] LOG listening on [::]:5432
2022-05-05 21:21:36.022 UTC [7] LOG process up: PgBouncer 1.16.1, libevent 2.1.8-stable (epoll), adns: c-ares 1.13.0, tls: OpenSSL 1.1.1k  FIPS 25 Mar 2021
2022-05-05 21:22:04.672 UTC [7] LOG C-0x560d3584bf70: (nodb)/(nouser)@10.42.2.0:37062 registered new auto-database: db=postgres
2022-05-05 21:22:04.691 UTC [7] WARNING DNS lookup failed: my-postgres-primary: result=0
2022-05-05 21:22:04.691 UTC [7] LOG S-0x560d3585bf10: postgres/_crunchypgbouncer@(bad-af):0 closing because: server DNS lookup failed (age=0s)
```

When I have logged in to the container and manually run `nslookup my-postgres-primary` command - it resolves correctly.

Could it be an issue with the outdated version of `adns: c-ares 1.13.0` (20-jun-2017)? I can see that there is a newer `1.8.1` (27-oct-2021) version available: [c-ares donwloads](https://c-ares.org/download/)

**Comment by nawarajshahi** [comment] 2022-05-06 16:26
@luber what does your cluster configuration look like? I was able to get pgbouncer working for the primary database as well as replica and it requires certain configuration to be enabled/set ahead of time or edit the cluster after you deploy for it to leverage pgbouncer.

**Comment by luber** [comment] 2022-05-08 11:38
@nawarajshahi here it is:
```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: my-postgres
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.2-1
  postgresVersion: 14
  service:
    type: NodePort    
  instances:
    - name: instance
      replicas: 3
      dataVolumeClaimSpec:
        storageClassName: "longhorn-single"
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi
      resources:
        limits:
          cpu: 2.0
          memory: 4Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: my-postgres
                  postgres-operator.crunchydata.com/instance-set: instance
  proxy:
    pgBouncer:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:ubi8-1.16-2
      replicas: 1
      service:
        type: NodePort
      config:
        global:
          pool_mode: transaction
          query_wait_timeout: "240"     
      resources:
        limits:
          cpu: 200m
          memory: 128Mi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: my-postgres
                  postgres-operator.crunchydata.com/role: pgbouncer
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.38-0
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            storageClassName: "longhorn"
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 20Gi
      manual:
        repoName: repo1
        options:
          - --type=full
      global:
        repo1-retention-full: "14"
        repo1-retention-full-type: time
  monitoring:
    pgmonitor:
      exporter:
        image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.1.0-0
  users:
    - name: postgres
    - name: admin
      options: "SUPERUSER"

  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          shared_preload_libraries: timescaledb
```

**Comment by nawarajshahi** [comment] 2022-05-12 17:47
@luber thanks for the spec. Upon looking more into it, I see that you need the following in your spec as well as some changes to be done once the cluster gets provisioned. 
```
  proxy:
    pgBouncer:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:ubi8-1.16-2
      replicas: 1
      service:
        type: NodePort
      config:
       databases:
          '*': host=pg-primary port=5432 #change this port if you're not using default 
        global:
          pool_mode: transaction
          query_wait_timeout: "240" 
          default_pool_size: "100"
          max_client_conn: "1000" #change depending on your app requirement
          server_tls_sslmode: verify-ca 
```
Deploy the pg cluster. 

Once deployed, find the primary pg pod and exec into primary pod
```
kubectl exec -it <pg-primary> -- bash -n <ns>
psql
\c <db-name>;
\ef pgbouncer.get_auth

#remove the line the following line
	#NOT pg_authid.rolsuper AND
#save and exit (wq)

\g 
\q

#if _crunchypgbouncer is not already a superuser you'll have to alter it to superuser 
psql
\du+ #to check the users and roles 
alter role _crunchypgbouncer with superuser;
\q
# This should be good enough! 

if you want to test this out, you can do 
psql postgres://<user-name>:<password>@pg-pgbouncer.pg.svc.cluster.local:5432/<db-name>
```
Hope this helps!

**Comment by luber** [comment] 2022-05-15 17:58
@nawarajshahi thanks for your help.
I have tried to follow the steps you described, but still can't connect. 

On primary pod:
```
bash-4.4$ psql -h my-pgbouncer -p 5432 -d postgres -U admin -W
Password: 
```

On pg-bouncer pod:
```
2022-05-15 17:53:21.976 UTC [7] WARNING DNS lookup failed: my-postgres-primary: result=0
2022-05-15 17:53:21.976 UTC [7] LOG S-0x564e8b518e50: postgres/_crunchypgbouncer@(bad-af):0 closing because: server DNS lookup failed (age=0s)
```

`pgbouncer.ini` from pg-bouncer secret:
```
# Generated by postgres-operator. DO NOT EDIT.
# Your changes will not be saved.

[pgbouncer]
%include /etc/pgbouncer/pgbouncer.ini

[pgbouncer]
auth_file = /etc/pgbouncer/~postgres-operator/users.txt
auth_query = SELECT username, password from pgbouncer.get_auth($1)
auth_type = scram-sha-256
auth_user = _crunchypgbouncer
client_tls_ca_file = /etc/pgbouncer/~postgres-operator/frontend-ca.crt
client_tls_cert_file = /etc/pgbouncer/~postgres-operator/frontend-tls.crt
client_tls_key_file = /etc/pgbouncer/~postgres-operator/frontend-tls.key
client_tls_sslmode = require
conffile = /etc/pgbouncer/~postgres-operator.ini
default_pool_size = 100
ignore_startup_parameters = extra_float_digits
listen_addr = *
listen_port = 5432
max_client_conn = 1000
pool_mode = transaction
query_wait_timeout = 240
server_tls_ca_file = /etc/pgbouncer/~postgres-operator/backend-ca.crt
server_tls_sslmode = verify-ca
unix_socket_dir =

[databases]
* = host=my-postgres-primary port=5432
```

**Comment by firemage722** [comment] 2022-05-17 17:52
I am also seeing a similar issue. I upgrade from pgo 5.0.5 to 5.1.0 this morning and since then the pgbouncer pods have been erroring out on DNS resolution errors. When I shell in to the pgbouncer pod and nslookup dbname-primary, it resolves just fine. I rolled back to 5.0.5 for the time being which has resolved the issue but I am unable to upgrade to the new version.

**Comment by andrewlecuyer** [comment] 2022-06-02 01:02
The DNS issues described in this thread should be addressed in both the PGO v5.0.6 and PGO v5.1.1 releases, which are now available in the [Crunchy Developer Portal](https://www.crunchydata.com/developers/):

https://www.crunchydata.com/developers/download-postgres/containers/postgres-operator-5x

More specifically, the DNS issue should be addressed by upgrading to the latest PgBouncer image:

```
registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:ubi8-1.16-3
```

Please feel free to reopen this issue, or to submit a new issue, if you continue to have trouble.

Thanks!

**Closed by andrewlecuyer** 2022-06-02 01:02 UTC

**Comment by firemage722** [comment] 2022-06-16 14:23
Confirmed working. Upgrade to PGO 5.1.1 today with all the new images and the DNS issues are no long there. Thank you!

**Comment by pere3** [comment] 2022-07-26 13:09
can you please explain what was causing this issue to happen? because i'm still having it even after upgrading to 5.1.2 and pgbouncer image
```
registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:ubi8-1.16-4
```

**Comment by leosussan** [comment] 2022-12-21 21:50
I'm getting this on 5.1.2 as well, though I am getting a slightly altered message:
`WARNING DNS lookup failed: my-postgres-primary: result=-2`

The result code is different (`-2` vs `0`) but the rest is the same
