### ISSUE TITLE
Question: Multimaster

### ISSUE THREAD

**Issue by Subetov** [CrunchyData/postgres-operator#3184] opened 2022-05-05 10:44 UTC
Is it possible to implement a multi-master solution in two separated data centers with the help of an operator?
Thank you very much in advance.

**Comment by benjaminjb** [comment] 2022-12-29 21:28
Pretty much a duplicate of https://github.com/CrunchyData/postgres-operator/issues/3153, yeah?

**Closed by benjaminjb** 2022-12-29 21:28 UTC
