### ISSUE TITLE
Adding env variables to Objects

### ISSUE THREAD

**Issue by Roia5** [CrunchyData/postgres-operator#2958] opened 2021-12-29 09:19 UTC
## Overview

Would love an option to add environment variables to objects created by the operator, most importantly StatefulSets of the postgres instances.

## Use Case

My use case is adding a TZ environment variable to change the default timezone in the postgres containers. This way pgbackrest PITR restores will be done more easily based on my users local time.

## Desired Behavior

Probably a field in the PostgresCluster CR where you can add environment variables, same as Annotations and Labels.

Any other idea on how to configure this automatically would be helpful.

## Environment

- Platform: `OpenShift`
- Platform Version: `4.6`
- PGO Image Tag: `ubi8-5.0.2-0`
- Postgres Version `14`

**Comment by jkatz** [comment] 2021-12-29 13:21
First, I would recommend updating to the latest patch release (5.0.4) as there are bug fixes and other improvements in it.

I don't think this would give you your desired result. Data stored in PostgreSQL is subject to your PostgreSQL timezone configuration, which you can read about in great detail here:

- https://www.postgresql.org/docs/current/datatype-datetime.html#DATATYPE-TIMEZONES

The pgBackRest docs recommend using a timestamp as generated by PostgreSQL to perform the PITR:

https://pgbackrest.org/user-guide.html#pitr

While pgBackRest will help you to set up a PITR, PostgreSQL itself is actually performing the recovery as it replays through the transactions, so it's important to provide a specific PostgreSQL configuration a time zone that is aligned to the time zone it's configured to for the reasons the pgBackRest docs list.

I would not be opposed to adding some more clarity to the PGO docs around the specific topic of time zones + PITR.

**Comment by ccpatrut** [comment] 2022-04-04 12:55
For me the issue was that I forgot to use the --set command for a restore type based on name. 

It helped me realize the problem the pgbackrest documentation for "target": 
https://pgbackrest.org/command.html#command-restore 

Defines the recovery target when --type is lsn, name, xid, or time. If the target is prior to the latest backup and --type is not time, then use the --set option to specify the backup set.

**Comment by benjaminjb** [comment] 2022-12-29 22:17
Duplicate/overlap of https://github.com/CrunchyData/postgres-operator/issues/3054

**Comment by andrewlecuyer** [comment] 2023-01-06 22:11
Per @benjaminjb this is a duplicate of #3054, so closing this specific issue.

Please see #3054 for additional information about this feature request.

**Closed by andrewlecuyer** 2023-01-06 22:11 UTC
Labels: duplicate, enhancement, v5, backlog
