### ISSUE TITLE
Add annotations to <cluster>-ha service

### ISSUE THREAD

**Issue by rectacoda** [CrunchyData/postgres-operator#3330] opened 2022-08-01 09:39 UTC
## Overview

Currently, inside the CR we can only set the sevice.type
We want to be able to also set annotations to the <cluster>-ha service

## Use Case

We use PGO in OCI (Oracle), as well as K8S on premise
Both have dynamic LB service, and dynamic DNS provisioning through external-dns RFC2136 provider.
To get an IP from the Oracle LB, we need to set the annotation: service.beta.kubernetes.io/oci-load-balancer-internal: "true"
To provision a dns for the service, we need to set the external-dns annotation: external-dns.alpha.kubernetes.io/hostname

## Desired Behavior

Add a spec.service.annotations to the CRD, to generate corresponding annotations on the <cluster>-ha service
Or a spec.service.serviceTemplate in order to provide fine-tuning for the <cluster>-ha service

## Environment

- Platform: Rancher managed K8S, on premise RKE, Oracle OKE
- Platform Version: 1.20.15 on premise, 1.21.5 OKE
- PGO Image Tag: ubi8-5.1.0-0
- Postgres Version 14
- Storage: Nutanix CSI LVM
- Number of Postgres clusters: 4

## Additional Information

Kind regards

**Comment by andrewlecuyer** [comment] 2022-08-01 14:48
@rectacoda thanks for reaching out!

This has been address in #3302, which will be included in the upcoming PGO v5.2.0 release.   Additionally, closing this as a duplicate of https://github.com/CrunchyData/postgres-operator/issues/3265.

**Closed by andrewlecuyer** 2022-08-01 14:48 UTC
