### ISSUE TITLE
Create login credentials secrets in several namespaces

### ISSUE THREAD

**Issue by juanmbellini** [CrunchyData/postgres-operator#3386] opened 2022-09-21 03:41 UTC
## Overview

As far as I understood from the documentation, when setting user stuff in a cluster manifest (with user access to the database), a secret with login credentials will be created in the same namespace where the cluster is deployed. But what if we want to access the database from other namespaces?

## Use Case

I would like to deploy database clusters in different namespaces than the ones from where the apps accessing them are running. So, it would be great that we could set in which namespaces the secrets with the login credentials are created.

## Desired Behavior

We could define in which namespaces the login credentials secrets are created in our cluster manifests.

## Environment

This feature would be environment agnostic. You would only need different namespaces in which databases and applications using these databases are deployed.

## Additional Information

Right now I'm just copying secrets between namespaces. I would like to avoid this step as I think is error prone, and also a bit insecure.

**Comment by benjaminjb** [comment] 2022-12-29 22:59
Seems like a duplicate of https://github.com/CrunchyData/postgres-operator/issues/2831, so closing this and also here to report that we have captured this in our backlog

**Closed by benjaminjb** 2022-12-29 22:59 UTC
Labels: duplicate
