### ISSUE TITLE
Set env vars in custom image in Postgres cluster

### ISSUE THREAD

**Issue by webcoderz** [CrunchyData/postgres-operator#3383] opened 2022-09-18 04:20 UTC
Is it possible to set env vars for the Postgres cluster on the manifest?, if so, where?

**Comment by benjaminjb** [comment] 2022-10-19 18:20
Duplicate of https://github.com/CrunchyData/postgres-operator/issues/3054

**Closed by benjaminjb** 2022-10-19 18:20 UTC
Labels: backlog
