### ISSUE TITLE
pgpool password doesnt work

### ISSUE THREAD

**Issue by k1ng440** [CrunchyData/postgres-operator#358] opened 2018-09-10 23:47 UTC
**I'm submitting a ...**

 
 - [x] bug report

**Do you want to request a *feature* or report a *bug*?**
 report a *bug*

**What is the current behavior?**
pgpool users are not being created on cluster creation.

**If the current behavior is a bug, please provide the steps to reproduce:**
pgo create cluster test --pgpool

cluster : ticker 
	psql -p 5432 -h 10.11.252.55 -U postgres postgres is Working
	psql -p 5432 -h 10.11.252.55 -U primaryuser postgres is Working
	psql -p 5432 -h 10.11.252.55 -U testuser userdb is Working
	psql -p 5432 -h 10.11.243.157 -U postgres postgres is NOT working
	psql -p 5432 -h 10.11.243.157 -U primaryuser postgres is NOT working
	psql -p 5432 -h 10.11.243.157 -U testuser userdb is NOT working

**What is the expected behavior?**
pgpool should be working

**What is the motivation or use case for changing the behavior?**
-

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, etc)
-

**Please tell us about your environment:**

 - Operating System: Ubuntu
 - Container Image Tag: centos7-3.2.0
 - Operator Version: 3.2.0
 - PostgreSQL Version: 10
 - Platform (Docker, Kubernetes, OpenShift): Kubernetes
 - Platform Version: 
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.5", GitCommit:"9b635efce81582e1da13b35a7aa539c0ccb32987", GitTreeState:"clean", BuildDate:"2018-08-02T23:42:40Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by cahoonpwork** [comment] 2018-09-11 13:53
Only the testuser is being configured with pgpool.  I tested the creation of a cluster with pgpool and it was working for me for the testuser.

Steps I used to try and reproduce:

 pgo create cluster pooltest --pgpool
 pgo show cluster pooltest

cluster : pooltest (centos7-10.5-2.1.0)
        deployment : pooltest
        deployment : pooltest-pgpool
        service : pooltest - ClusterIP (10.3.253.58)
        service : pooltest-pgpool - ClusterIP (10.3.250.191)
        labels : pgpool-secret= pgo-backrest=false pgo-version=3.2 crunchy-pgbadger=false crunchy-pgpool=true crunchy_collect=false name=pooltest pg-cluster=pooltest primary=true archive=false archive-timeout=60
 pgo test pooltest

cluster : pooltest
        psql -p 5432 -h 10.3.253.58 -U postgres postgres is Working
        psql -p 5432 -h 10.3.253.58 -U primaryuser postgres is Working
        psql -p 5432 -h 10.3.253.58 -U testuser userdb is Working
        psql -p 5432 -h 10.3.250.191 -U postgres postgres is NOT working
        psql -p 5432 -h 10.3.250.191 -U primaryuser postgres is NOT working
        psql -p 5432 -h 10.3.250.191 -U testuser userdb is Working


My guess is that this is related to your issue 355, and the secrets were never cleaned up properly since the cluster name "test" is the same.  What type of storage are you using?  Can you either try again with a cleaned up test cluster.  Let me know what happens.

**Comment by cahoonpwork** [comment] 2018-09-13 14:00
We have an issue for updating operator to handle this: https://github.com/CrunchyData/postgres-operator/issues/156

**Comment by KrzysztofWloch** [comment] 2018-09-25 11:44
Fixed in #156 , released in https://github.com/CrunchyData/postgres-operator/tree/3.3.0-rc3

**Comment by jmccormick2001** [comment] 2018-10-12 22:02
should be fixed with the 3.3.0 release.

**Closed by jmccormick2001** 2018-10-12 22:02 UTC
