### ISSUE TITLE
Pgo backup Jobs should not be deleted 

### ISSUE THREAD

**Issue by NiraimathiGunalan** [CrunchyData/postgres-operator#1032] opened 2019-10-01 10:08 UTC
In centos7-4.0.1 image (platform kubernetes), the backup occurring first time alone and cannot be able to create after that. 
The reason behind this is Backup job have been given with same name every-time so the Pgtask getting created cannot be recreated with same name.

<img width="600" alt="Screenshot 2019-10-01 at 10 53 52" src="https://user-images.githubusercontent.com/54842069/65952935-d2f4b780-e43a-11e9-84d8-5c74a1a3ce46.png">

Ref: https://github.com/CrunchyData/postgres-operator/issues/140 
This issue refers the same and the solution given here is to automatically delete the backup job. But the log of all backups are necessary. 

The job name of backup as mentioned in https://github.com/CrunchyData/postgres-operator/blob/master/operator/backrest/backup.go#L60 can be added with **+ "-" + util.RandStringBytesRmndr(4),** same as restore.

**Comment by andrewlecuyer** [comment] 2019-10-01 14:47
@NiraimathiGunalan this appears to be a duplicate of #964, which is a known issue that has been addressed in #907 and will be included in the next PGO release (v4.1.0).

A workaround for v4.0.1 can be found in the following comment https://github.com/CrunchyData/postgres-operator/issues/964#issuecomment-532374267.

**Comment by NiraimathiGunalan** [comment] 2019-10-01 14:56
Closing this issue since it is the duplicate of https://github.com/CrunchyData/postgres-operator/issues/964

**Comment by NiraimathiGunalan** [comment] 2019-10-07 10:04
The release tag(v4.1.0) solved the issue by automatically deleting the backup job. But the logs of every backup jobs are necessary for future investigation and also to investigate backup failure at any condition. Reopening this issue to retain the backup jobs.

**Comment by jkatz** [comment] 2019-12-31 21:46
On `v4.2.0` I have confirmed that the backup jobs persist even after they complete, regardless of outcome. As a result, the logs are available.

**Closed by jkatz** 2019-12-31 21:46 UTC
