### ISSUE TITLE
Update the password for postgres super user

### ISSUE THREAD

**Issue by vg02111989** [CrunchyData/postgres-operator#1906] opened 2020-09-22 05:51 UTC
Hi,

I want to set the password for postgres user while creating the cluster by option --password-superuser=Postgres@123
but I am not able to use this when trying to access using client.

Can anyone suggest, how I can change the password as when using command
**pgo update user postgres**

Its giving me error like, not able change the password of system account

**Comment by jkatz** [comment] 2020-09-24 21:59
I guess I'm curious what your use case is? What are you doing with the `postgres` account where you would like to change its password?

Are you normally logging in as the `postgres` user? If you are, what activities are you doing with it?

Perhaps like #1887 we may need to relax the restrictions on updating system accounts...though really these should not be logged in. Perhaps it would be better to create a new account with superuser privileges and use that?

**Comment by vg02111989** [comment] 2020-09-25 11:14
Hey Jonathan

I am creating a cluster using pgo cli with one replica
I want to create multiple databases inside same postgres instance, for creating database I would require super user privileges.

In my use case, if I am setting the password while creating cluster by giving option **_--password-superuser=Postgres@123_** , password will get set for postgres user, but when trying to login using the same, its giving authentication failure because as you had suggested in another thread, password of super user not updated in kubernetes secrets.

In the scenario when I will not set the superuser password while creating db cluster and when I give the command as **_ pgo show user --show-system-accounts_** , it gave some system generated password.
I want to update that password in order to provide some readable static password to my application

**Comment by jkatz** [comment] 2020-09-25 13:15
What version of the PostgreSQL Operator are you running? I can't reproduce this issue.

```
pgo create cluster zebra --password-superuser=custom
created cluster: zebra
workflow id: 7bf93198-5190-47fe-ac61-917438c29c7c
database name: zebra
users:
	username: testuser password: <REDACTED>

pgo show user zebra --show-system-accounts

CLUSTER USERNAME    PASSWORD                 EXPIRES STATUS ERROR 
------- ----------- ------------------------ ------- ------ -----
zebra   crunchyadm                           never   ok           
zebra   postgres    custom                   never   ok           
zebra   primaryuser <REDACTED>               never   ok           
zebra   testuser    <REDACTED>               never   ok

**Comment by jkatz** [comment] 2020-10-05 20:40
Closing this due to being unable to reproduce the issue. If you are able to provide more information about it, I would be happy to look into this further. Thanks!

**Closed by jkatz** 2020-10-05 20:40 UTC
