### ISSUE TITLE
pgbouncer-config contatiner OOMKilled

### ISSUE THREAD

**Issue by momoadc** [CrunchyData/postgres-operator#2673] opened 2021-09-05 16:38 UTC
Please ensure you do the following when reporting a bug:

- [x] Provide a concise description of what the bug is.
- [x] Provide information about your environment.
- [ ] Provide clear steps to reproduce the bug.
- [ ] Attach applicable logs. Please do not attach screenshots showing logs unless you are unable to copy and paste the log data.
- [ ] Ensure any code / output examples are [properly formatted](https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code) for legibility.

Note that some logs needed to troubleshoot may be found in the `/pgdata/<CLUSTERNAME>/pg_log` directory on your Postgres instance.

An incomplete bug report can lead to delays in resolving the issue or the closing of a ticket, so please be as detailed as possible.

If you are looking for [general support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/), please view the [support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/) page for where you can ask questions.

Thanks for reporting the issue, we're looking forward to helping you!

## Overview

Im running the PostgresCluster with resource requests and limits for the main components.
I noticed that the pgbouncer pod entring CrashLoopBack state every once in a while. 
While I digged deeper I noticed that the pgbouncer-config is OOMKilled. 
I configured resources for the pgbouncer pod but the resources for the pgboucner-config container are hardcoded.
Am i missing the configuration from the CRD or is it reallly hardcoded?
Apache Airflow is connected to the database using pgbouncer. There are less than 20 connections while the application is idle but the pgboucner-config is still receiving OOMKilled

## Environment

Please provide the following details:

- Platform: OpenShift
- Platform Version:  4.6.5
- PGO Image Tag: ubi-5.0.1-0
- Postgres Version: 13
- Storage: isilon storageclass

### REPRO

Provide steps to get to the error condition:

1. I created a Helm Chart to allow adding more features to the CR
2. I deployed the Chart with resources limits and requests under a namespace with ResourceQuota.
3. I connected Apache Airflow to the PostgresCluster using the pgbouncer URI
4. After some time, the pgbouncer-config container restarts due to OOMKilled

## Logs

I cannot add logs since I work in a restricted network.

**Comment by jkatz** [comment] 2021-09-06 16:59
> I created a Helm Chart to allow adding more features to the CR

Can you provide the Helm chart? If you're "adding more features" that adds a major variable into trying to determine what's going on.

The lack of logs also will make this a bit trickier to assess.

**Comment by noamendel** [comment] 2021-09-06 17:35
I can send the generated PostgresCluster manifest.

**Comment by noamendel** [comment] 2021-09-07 09:41
I found out that if you define resources for the pgBouncer container the pgbouncer-config container will be defined with hardcoded resources
https://github.com/CrunchyData/postgres-operator/blob/b284ed4ee4e51bf009ed1060315baefadcb66811/internal/pgbouncer/reconcile.go#L205
When I monitored the pgBouncer pod I witnessed that the pgbouncer-config container have memory peaks of ~50Mi and therefore receives OOMKilled
Is it possible to allow customizable resources for the pgbouncer-config as well?

**Comment by cbandy** [comment] 2021-09-10 14:11
Thank you for the report. I saw similar behavior in the past with a different version of the container command. The amount of memory required varies depending on the container runtime. We're considering how to expose the details of this sidecar in the spec.

I'd like to investigate this further with you if you're able. I'm curious how much memory is ultimately required in your environment.

The following patch to your PgBouncer deployment adds another sidecar with a different command. This one should require less memory and you can adjust the limit to find a suitable value for your runtime. Be sure to match the image to the one already in the deployment. What memory usage do you see and what limit eliminates restarts?

```bash
# add sidecar
oc patch deploy/mycluster1-pgbouncer -p "$(cat pgbouncer.yaml)"

# remove sidecar
oc patch deploy/mycluster1-pgbouncer -p '{"spec":{"template":{"spec":{"containers":[{"$patch":"delete","name":"pgbouncer-config-builtin"}]}}}}'
```

```yaml
spec:
  template:
    spec:
      containers:
      - name: pgbouncer-config-builtin
        image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:centos8-1.15-1  # adjust image
        resources:
          limits: { cpu: 5m, memory: 16Mi }  # adjust resources
        command:
        - bash
        - -ceu
        - --
        - |-
          monitor() {
          exec {fd}<> <(:)
          while read -t 5 -u "${fd}" || true; do
            if [ "${directory}" -nt "/proc/self/fd/${fd}" ] && pkill --signal HUP --exact pgbouncer
            then
              exec {fd}>&- && exec {fd}<> <(:)
              stat --format='Loaded configuration dated %y' "${directory}"
            fi
          done
          }; export directory="$1"; export -f monitor; exec -a "$0" bash -ceu monitor
        - pgbouncer-config
        - /etc/pgbouncer
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        volumeMounts:
        - { mountPath: /etc/pgbouncer, name: pgbouncer-config, readOnly: true }
```

**Comment by momoadc** [comment] 2021-09-29 13:37
Sorry for the long delay.
The original sidecar has CPU picks up to 90M-100M and starts throttling which is followed by memory consumption of 20MiB-50MiB and therefore OOMKilled.
Running the additional sidecar with 10m and 50Mi (which is a bit overkill) having no issues.

**Comment by momoadc** [comment] 2021-09-29 16:16
from running kubectl top pod --containers, pgboucner-config-builting stabilizes on 0m-4m CPU and 10Mi-15Mi memory

**Comment by iosifnicolae2** [comment] 2022-02-03 09:32
@cbandy are you planning to merge your fix into the main repository? :)

Thank you!

**Comment by iosifnicolae2** [comment] 2022-02-03 09:44
The `pgbouncer-config` container is still throttling even though the CPU limits are not reached and the memory usage is ok..
![image](https://user-images.githubusercontent.com/7108834/152317894-fdcda916-819f-4324-888e-e98a51b15fa0.png)
![image](https://user-images.githubusercontent.com/7108834/152318093-cde53bea-9b18-43d1-865c-4a51646a659e.png)

PS. I'm experiencing degraded performance when using pgbouncer, and I don't know why.. (this might not be related with the initial problem..)

**Comment by cbandy** [comment] 2022-02-03 15:08
@iosifnicolae2 The CPU limits of this sidecar can be adjusted since PGO v5.0.3: https://access.crunchydata.com/documentation/postgres-operator/v5/references/crd/#postgresclusterspecproxypgbouncersidecars

What distro and version of Kubernetes is this on? What limit relieves the throttling for you?

**Comment by iosifnicolae2** [comment] 2022-02-03 15:48
@cbandy 
Kubernetes is using `K3S v1.21.5`
The nodes are using `Ubuntu 20.04.3 LTS`
I've allocated 100m cpu and 256Mi RAM. I'll test these settings in the next days to see if the poor performance was caused by this problem.

Thank you!

**Comment by iosifnicolae2** [comment] 2022-02-04 11:00
It seems that after I've raised the limits of `config-reloader` container the pgBouncer performance problems have been solved too.

**Comment by cbandy** [comment] 2022-05-03 18:17
The resource requirements for this sidecar should have been reduced a bit in v5.1.0 with https://github.com/CrunchyData/postgres-operator/pull/2817. Marking this as solved.

**Closed by cbandy** 2022-05-03 18:18 UTC
Labels: question, v5
