### ISSUE TITLE
Create Cluster with postgis-Image generates errors when selecting the backrest-image

### ISSUE THREAD

**Issue by Schmaetz92** [CrunchyData/postgres-operator#2291] opened 2021-02-19 16:21 UTC
**Describe the bug**
If a cluster is created based on the Postgis image, the Backrest pod tries to load the image with the Postgis version in the tag. 
example: crunchy-backrest-repo:centos8-12.6-3.0-4.6.1 - instead of crunchy-backrest-repo:centos8-12.6-4.6.1

**To Reproduce**
1. Use the pgo-client and the operator version 4.6.1
2. pgo create cluster testcluster --ccp-image=postgres-gis-ha --ccp-image-tag=centos8-12.6-3.0-4.6.1
3. Go to the created backrest pod and look in the yaml-file for the image of the pod.

**Expected behavior**
Normally, the image should be selected correctly. In the example above, crunchy-backrest-repo:centos8-12.6-4.6.1 should be selected.

**Please tell us about your environment:**

* Operating System: Centos8
* Where is this running ( Local, Cloud Provider): Cloud Provider
* Container Image Tag: 4.6.1 (centos8-12.5-3.0-4.6.1)
* Operator Image Tag: 4.6.1 (centos8-4.6.1)
* PostgreSQL Version: 12.5
* Platform (Docker, Kubernetes, OpenShift): OpenShift
* Platform Version: 4.6.13

**Additional context**
I have already observed this behaviour with version 4.6.0 during the upgrade process.

**Comment by jkatz** [comment] 2021-02-19 16:57
I was unable to reproduce this with the steps provided. The image tag issue on upgrade was addressed in #2264 and available with 4.6.1 (which was just pushed out moments ago).

There was a separate issue with the `pgo create cluster` command that was addressed several releases ago -- I can't find the commit.

Without additional logs or an understanding of which containers you are using (there is a bunch of different tags listed above), I'm not sure what the exact issue is.

**Comment by Schmaetz92** [comment] 2021-02-22 06:11
Hi,
i used the pre-release of 4.6.1 for testing, which was already available. (Not rc1)

Which container do I use: 
prefix: registry.developers.crunchydata.com
Image: postgres-gis-ha
Image tag: centos8-12.6-3.0-4.6.1 / centos8-13.2-3.0-4.6.1
-> Backrest pod (events)

Back-off pulling image "registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest-repo:centos8-13.2-3.0-4.6.1"

In the tag, the Postgis version (3.0 in this case) also shows up in the backrest. However, the tag should read Back-off pulling image centos8-13.2-4.6.1 or centos8-12.6-4.6.1.


I have attached logs of the operator.

Many greetings


[operator.log](https://github.com/CrunchyData/postgres-operator/files/6019809/operator.log)

**Comment by Schmaetz92** [comment] 2021-02-22 13:40
Hi, 
the problem is bigger than thought. 
It doesn't just affect the PG backrest pod, it basically affects all pods. 
Currently tested:
- PGBackrest
- backrest-create-stanza
- backrest-backup (crunchy-pgbackrest:centos8-12.6-3.0-4.6.1)
- PGBouncer (crunchy-pgbouncer:centos8-12.6-3.0-4.6.1)

With each image, the postgis version is added as in tag. 

I have this morning the operator again freshly obtained and updated (V 4.6.1)

What more information can I give you to identify the problem? 
If you need more logs, which ones exactly?

**Comment by jkatz** [comment] 2021-03-04 22:34
```
pgo create cluster testcluster --ccp-image=postgres-gis-ha --ccp-image-tag=centos8-12.6-3.0-4.6.1
```

will not work. I have verified this. The reason is because the name of the image is `crunchy-postgres-gis-ha`.

```
pgo create cluster testcluster --ccp-image=crunchy-postgres-gis-ha --ccp-image-tag=centos8-12.6-3.0-4.6.1
```

works fine. I was able to create all of the sidecars mentioned.

**Closed by jkatz** 2021-03-04 22:34 UTC
Labels: question
