### ISSUE TITLE
[BUG] metadata.annotations too long when applying postgresclusters CRD

### ISSUE THREAD

**Issue by jaitaiwan** [CrunchyData/postgres-operator#3938] opened 2024-06-21 03:19 UTC
Hey folks,

When running an apply on the current CRD https://raw.githubusercontent.com/CrunchyData/postgres-operator-examples/main/helm/install/crds/postgres-operator.crunchydata.com_postgresclusters.yaml the following error occurs:
The CustomResourceDefinition "postgresclusters.postgres-operator.crunchydata.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes

I imagine this is not supposed to happen?

**Comment by andrewlecuyer** [comment] 2024-06-21 18:31
Hi @jaitaiwan!  This is actually a duplicate of https://github.com/CrunchyData/postgres-operator/issues/3633.

And as you can see in that other thread, the answer is to use [Server-Side Apply](https://kubernetes.io/docs/reference/using-api/server-side-apply/) when applying your changes, e.g. as follows:

```bash
kubectl apply --server-side
```

This is specifically due to a limitation with `kubectl apply` (and more specifically how it tracks/uses the `last-applied-configuration`) rather than anything specific to CPK, that Server-Side Apply should directly address.

Hope this helps!

**Closed by andrewlecuyer** 2024-06-21 18:31 UTC
Labels: duplicate, question
