### ISSUE TITLE
documentation on how to reinitialize s3. 

### ISSUE THREAD

**Issue by gauravshankarcan** [CrunchyData/postgres-operator#1657] opened 2020-06-22 13:06 UTC
** Which example are you working with? **
Crunchy 4.3.2

**What is the current behavior?**
S3 is configured on start, log shipping occurs at start

**What is the expected behavior?**
if a cluster is already defined, how do we change the s3 target and restart WAL logs to be sent from the beginning ?

**Other information** (e.g. detailed explanation, related issues,  etc)
NA

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local , Cloud Provider) local s3 , on prem operator
* Storage being used (NFS, Hostpath, Gluster, etc): NFS / minio s3
* Container Image Tag: 4.3.2
* PostgreSQL Version: 12.3
* Platform (Docker, Kubernetes, OpenShift): openshift
* Platform Version: 4.3.2

If possible please run the following on the kubernetes or OpenShift (oc) commands and provide the result:
 kubectl describe yourPodName
 kubectl describe pvc
 kubectl get nodes
 kubectl log yourPodName

---------

More of an info question as I couldn't find any in the documentation on how to reinitialize s3.

**Comment by jkatz** [comment] 2020-06-22 13:07
Duplicate of #1610

**Closed by jkatz** 2020-06-22 13:07 UTC
