### ISSUE TITLE
Disable backups

### ISSUE THREAD

**Issue by Martin-Hogge** [CrunchyData/postgres-operator#3156] opened 2022-04-19 13:56 UTC
Hi !

Simple question: is their a way to completely disable backup and wal archiving of a cluster ? We are having issues with disks being filled too quickly and we would like to stop backups while we are looking for a better backup strategy / having more available spaces. I would like to be sure no WAL nor no backups will be filling my disk while we are searching for a better solution, is it possible ? (knowing the consequences of having no backups, I'll maybe do some backup manually in case it's taking too much time).

Thank you.

**Comment by sagikazarmark** [comment] 2022-04-23 19:08
Seems like a duplicate of #3152

**Comment by benjaminjb** [comment] 2023-01-03 19:08
@Martin-Hogge I'm going to close this ticket as a duplicate -- it's actually a feature that has come up a few times and that we have in our backlog. I haven't had the opportunity/need to check out some workarounds, but check out this as a possibility: https://github.com/CrunchyData/postgres-operator/issues/2531#issuecomment-1022070211

Future updates to this feature request will probably occur on a still open ticket, which will probably end up being the oldest ticket with this issue.

**Closed by benjaminjb** 2023-01-03 19:08 UTC
Labels: duplicate
