### ISSUE TITLE
postgres-db-stanza-create unable to find primary cluster in k8s

### ISSUE THREAD

**Issue by swapnil-raj** [CrunchyData/postgres-operator#2690] opened 2021-09-13 09:24 UTC
pgo
 - client version 4.7.2
 - apiserver version 4.7.2

k8s
 - Client Version: v1.21.2
 - Server Version: v1.20.2

I deployed pgo operator using [https://raw.githubusercontent.com/CrunchyData/postgres-operator/v4.7.2/installers/kubectl/postgres-operator.yml](https://raw.githubusercontent.com/CrunchyData/postgres-operator/v4.7.2/installers/kubectl/postgres-operator.yml) after adding backrest_aws configrations.

installed pgo clint using [https://raw.githubusercontent.com/CrunchyData/postgres-operator/v4.7.2/installers/kubectl/client-setup.sh ](https://raw.githubusercontent.com/CrunchyData/postgres-operator/v4.7.2/installers/kubectl/client-setup.sh 
)

Then Created pods and backup jobs using pgo operator.

currently the namespace has following pods 
```
NAME                                                READY   STATUS      RESTARTS   AGE
pgo-deploy-zmp97                                    0/1     Completed   0          4d22h
postgres-db-7745d858d8-hhggx                        2/2     Running     0          3d5h
postgres-db-backrest-shared-repo-747999d85b-b2rs2   1/1     Running     0          3d5h
postgres-db-incr-sch-backup-6zzw8                   0/1     Error       0          8h
postgres-db-incr-sch-backup-gnm7r                   0/1     Error       0          7h50m
postgres-db-incr-sch-backup-qq7xp                   0/1     Error       0          7h57m
postgres-db-incr-sch-backup-rxhcv                   0/1     Error       0          8h
postgres-db-incr-sch-backup-tbjkf                   0/1     Error       0          8h
postgres-db-incr-sch-backup-txskm                   0/1     Error       0          8h
postgres-db-incr-sch-backup-vwqs8                   0/1     Error       0          7h39m
postgres-db-stanza-create-6qkxl                     0/1     Error       0          3d4h
postgres-db-stanza-create-759cg                     0/1     Error       0          3d4h
postgres-db-stanza-create-8qq78                     0/1     Error       0          3d4h
postgres-db-stanza-create-dcxwx                     0/1     Error       0          3d4h
postgres-db-stanza-create-gpmf7                     0/1     Error       0          3d4h
postgres-db-stanza-create-lswct                     0/1     Error       0          3d4h
postgres-db-stanza-create-xrgs8                     0/1     Error       0          3d4h
postgres-operator-5c8f5dd5cb-kmn6h                  4/4     Running     1          4d22h
```
postgres-db-stanza-create- is giving these logs - 
```
time="2021-09-10T04:18:27Z" level=info msg="crunchy-pgbackrest starts"
time="2021-09-10T04:18:27Z" level=info msg="debug flag set to false"
time="2021-09-10T04:18:27Z" level=info msg="backrest stanza-create command requested"
time="2021-09-10T04:18:27Z" level=info msg="s3 flag enabled for backrest command"
time="2021-09-10T04:18:27Z" level=info msg="command to execute is [pgbackrest stanza-create  --db-host=192.168.82.23 --db-path=/pgdata/postgres-db --repo1-type=s3 --no-repo1-s3-verify-tls]"
time="2021-09-10T04:18:27Z" level=info msg="output=[]"
time="2021-09-10T04:18:27Z" level=info msg="stderr=[WARN: unable to check pg-1: [UnknownError] remote-0 process on '192.168.82.23' terminated unexpectedly [255]: ssh: connect to host 192.168.82.23 port 22: Connection refused\nERROR: [056]: unable to find primary cluster - cannot proceed\n]"
time="2021-09-10T04:18:27Z" level=fatal msg="command terminated with exit code 56"
```
postgres-db-incr-sch-backup is giving these logs -
```
nss_wrapper: user exists
nss_wrapper: group exists
nss_wrapper: environment configured
Mon Sep 13 00:09:26 UTC 2021 INFO: Image mode found: pgbackrest
Mon Sep 13 00:09:26 UTC 2021 INFO: Starting in 'pgbackrest' mode
time="2021-09-13T00:09:26Z" level=info msg="crunchy-pgbackrest starts"
time="2021-09-13T00:09:26Z" level=info msg="debug flag set to false"
time="2021-09-13T00:09:26Z" level=info msg="backrest backup command requested"
time="2021-09-13T00:09:26Z" level=info msg="s3 flag enabled for backrest command"
time="2021-09-13T00:09:26Z" level=info msg="command to execute is [pgbackrest backup --stanza=db --type=incr  --db-host=192.168.82.23 --db-path=/pgdata/postgres-db --repo1-type=s3 --no-repo1-s3-verify-tls]"
time="2021-09-13T00:20:30Z" level=info msg="output=[]"
time="2021-09-13T00:20:30Z" level=info msg="stderr=[WARN: option 'repo1-retention-full' is not set for 'repo1-retention-full-type=count', the repository may run out of space\n      HINT: to retain full backups indefinitely (without warning), set option 'repo1-retention-full' to the maximum.\nERROR: [101]: unable to load info file '/backrestrepo/postgres-db-backrest-shared-repo/backup/db/backup.info' or '/backrestrepo/postgres-db-backrest-shared-repo/backup/db/backup.info.copy':\n       ServiceError: TLS error [1:336130315] wrong version number\n       ServiceError: TLS error [1:336130315] wrong version number\n       HINT: backup.info cannot be opened and is required to perform a backup.\n       HINT: has a stanza-create been performed?\n]"
time="2021-09-13T00:20:30Z" level=fatal msg="command terminated with exit code 101"
```
when i exec into `postgres-db-backrest-shared-repo-747999d85b-b2rs2 ` and use the command
`pgbackrest info --repo1-type s3` it gives output -
```
stanza: db
    status: error (other)
            [ServiceError] TLS error [1:336130315] wrong version number
    cipher: none
```

What can be the possible error and how it can be resolved?

**Comment by jkatz** [comment] 2021-09-16 18:31
`TLS error [1:336130315] wrong version number`

It sounds like there is something wrong with your TLS certificates. Looking further into it, this appears to be a duplicate of #2421, which was resolved with updating configuration.

**Closed by jkatz** 2021-09-16 18:31 UTC
Labels: duplicate, question, v4
