### ISSUE TITLE
Crunchy postgres for kubernetes v5.2.0 Cannot be installed using redhat operatorhub - missing/unknown pgo Image digest

### ISSUE THREAD

**Issue by sanju7216** [CrunchyData/postgres-operator#3506] opened 2022-12-19 12:32 UTC
Please ensure you do the following when reporting a bug:

- [x] Provide a concise description of what the bug is.
- [ ] Provide information about your environment.
- [x] Provide clear steps to reproduce the bug.
- [x] Attach applicable logs. Please do not attach screenshots showing logs unless you are unable to copy and paste the log data.
- [ ] Ensure any code / output examples are [properly formatted](https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code) for legibility.

Note that some logs needed to troubleshoot may be found in the `/pgdata/<CLUSTERNAME>/pg_log` directory on your Postgres instance.

An incomplete bug report can lead to delays in resolving the issue or the closing of a ticket, so please be as detailed as possible.

If you are looking for [general support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/), please view the [support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/) page for where you can ask questions.

Thanks for reporting the issue, we're looking forward to helping you!

## Overview

We are unable to crunchy postgres for kubernetes operator using redhat operatorhub, is there a workaround or any fix for this??
As this is a dependency for our product, its blocking customers to use our product.

Looks like `registry.connect.redhat.com/crunchydata/postgres-operator@sha256:4ad944f4f01a85249aa7678521e61fe48ed150ac43f3c38f33b42f7a32eb9961` is unavailable

```
Failed to pull image "registry.connect.redhat.com/crunchydata/postgres-operator@sha256:4ad944f4f01a85249aa7678521e61fe48ed150ac43f3c38f33b42f7a32eb9961": rpc error: code = Unknown desc = reading manifest sha256:4ad944f4f01a85249aa7678521e61fe48ed150ac43f3c38f33b42f7a32eb9961 in registry.connect.redhat.com/crunchydata/postgres-operator: manifest unknown: manifest unknown
```

<img width="1269" alt="Screenshot 2022-12-19 at 12 24 02" src="https://user-images.githubusercontent.com/728940/208425493-7fb880ab-aa65-4819-940e-d96e0e48c5d3.png">
<img width="963" alt="Screenshot 2022-12-19 at 12 25 24" src="https://user-images.githubusercontent.com/728940/208425714-b06b2484-667c-4104-b1b9-f0266e6b8c0a.png">

## Environment

Please provide the following details:

- Platform: (`Kubernetes`, `OpenShift`, `Rancher`, `GKE`, `EKS`, `AKS` etc.)
- Platform Version: (e.g. `1.20.3`, `4.7.0`)
- PGO Image Tag: (e.g. `ubi8-5.3.0-0`)
- Postgres Version (e.g. `14`)
- Storage: (e.g. `hostpath`, `nfs`, or the name of your storage class)

### REPRO

Provide steps to get to the error condition:

1. Run `...`
1. Do `...`
1. Try `...`

### EXPECTED

1. Provide the behavior that you expected.

### ACTUAL

1. Describe what actually happens

## Logs

Please provided appropriate log output or any configuration files that may help troubleshoot the issue. **DO NOT** include sensitive information, such as passwords.

## Additional Information

Please provide any additional information that may be helpful.

**Comment by benjaminjb** [comment] 2022-12-29 20:53
I'm going to close this as a duplicate of https://github.com/CrunchyData/postgres-operator/issues/3504 since we're working on it there.

**Closed by benjaminjb** 2022-12-29 20:53 UTC
