### ISSUE TITLE
pgAdmin and additional tools

### ISSUE THREAD

**Issue by edenkoveshi** [CrunchyData/postgres-operator#2754] opened 2021-10-04 14:20 UTC
## Overview

Hi, I think it would be nice to have the option to deploy pgAdmin (just like in v4),as well as other pg tools, as another deployment or as a sidecar container.

## Use Case

Extending PG instances easily.
## Desired Behavior

One option would be to simply add spec fields for additional containers/deployments.
Another option is to specifically add a _pgAdmin_ field (just like _pgBouncer_)

## Environment

Tell us about your environment:

Please provide the following details:

- Platform: `Kubernetes`, `OpenShift`
- Platform Version: `1.22`, `4.6.0`
- PGO Image Tag: `ubi8-5.0.2-0`

## Additional Information
This will also help https://github.com/CrunchyData/postgres-operator/issues/2636 and https://github.com/CrunchyData/postgres-operator/issues/2618

**Comment by jkatz** [comment] 2021-10-04 14:22
Thanks for the suggestion. I'm marking this as a duplicate of #2618  for the request of sidecar functionality, and partially a duplicate of #2636 for the request of pgAdmin 4 functionality.

pgAdmin 4 is currently on the roadmap.

**Closed by jkatz** 2021-10-04 14:22 UTC
Labels: duplicate, v5
