### ISSUE TITLE
Possibility to change log level in the Postgres Cluster yaml

### ISSUE THREAD

**Issue by cassanellicarlo** [CrunchyData/postgres-operator#3621] opened 2023-03-30 13:36 UTC
## Overview

We would like to be able to set the logging level for the Postgres cluster in the yaml configuration.

## Use Case

Too many logs are produced and not really useful.

## Desired Behavior

A variable, LOG_LEVEL, that can be set

## Environment

- Platform: OpenShift
- Platform Version: 4.10
- Postgres Version: 14

**Comment by dsessler7** [comment] 2023-04-03 17:26
Hello @cassanellicarlo, given that there are many different components that can be creating logs in any given PostgresCluster (Postgres, pgbackrest, pgbouncer, Patroni, etc.), which one are you concerned about when it comes to having finer control of the logging?

**Comment by cassanellicarlo** [comment] 2023-04-18 08:30
Patroni.

**Comment by dsessler7** [comment] 2023-04-18 16:40
We have a story in our dev backlog for making the PATRONI_LOG_LEVEL environment variable available for adjustment via Crunchy Postgres for Kubernetes.

**Comment by cassanellicarlo** [comment] 2023-06-27 12:16
What's the status here? When will this feature be implemented?

**Comment by benjaminjb** [comment] 2023-07-07 17:53
As this seems to be a duplicate of https://github.com/CrunchyData/postgres-operator/issues/3451, I'm going to close this issue. Future updates to this topic will happen on that other Github issue.

**Closed by benjaminjb** 2023-07-07 17:53 UTC
Labels: enhancement, triaged, backlog
