### ISSUE TITLE
postgres-repo-host pod in CrashLoopBackOff - "environment: /dev/fd/62: Text file busy"

### ISSUE THREAD

**Issue by getkedar1981** [CrunchyData/postgres-operator#3318] opened 2022-07-26 04:46 UTC
We have a 3 node kubernetes cluster and deployed these examples in a namespace. ( PGO was deployed in namespace and not clusterwide )

This was deployed using steps shared under : https://access.crunchydata.com/documentation/postgres-operator/5.0.0/quickstart/

We have tried cluster wide operator and namespace based too ( using kustomize ) . In both cases this issue was seen.
Steps : 
- After installation ,delete the pod "postgres-repo-host-0" and it enters CrashLoopBackOff state on restart.

Observed that the postgres-repo-host-0 pod goes into CrashLoopBackOff with container 'pgbackrest-config' shows logs as "environment: /dev/fd/62: Text file busy"

**_#kubectl logs postgres-repo-host-0 pgbackrest-config -n postgres-operator
environment: /dev/fd/62: Text file busy_**

The pod postgres-repo-host-0 had to be restarted a few times to come back to running state. It may or may not come in Running state after few pod reboots.

This was observed on k8s v1.19/1.20 and PGO v 5.0.0, 5.1.0 and also latest ones.

Its seems the monitor function - as part 'pgbackrest-config' container - is generating this error at step -> exec {fd}<> <(:)

Can you please suggest if this is a known issue and any workaround/solution for this issue?

I have also opened a bug under examples : https://github.com/CrunchyData/postgres-operator-examples/issues/144 but got no reply for this there.

**Comment by andrewlecuyer** [comment] 2022-07-30 01:12
@getkedar1981 we are not seeing this issue in any of our various Kubernetes test environments.

Can you provide additional details about your specific Kubernetes environment?  This issue currently appears to be environment specific.

**Comment by getkedar1981** [comment] 2022-08-03 05:16
> @getkedar1981 we are not seeing this issue in any of our various Kubernetes test environments.
> 
> Can you provide additional details about your specific Kubernetes environment? This issue currently appears to be environment specific.

Hi Andrew,

    We have kubernetes 1.19 and 1.20  - 3 node clusters with our CSI and CNI to use our hardware. On this cluster, downloaded the examples zip from git repo for PGO 5.1.1 / 5.1.2  and was able to create a PGO and postgres cluster with the steps given on your docs page. However above issue was observed after the postgres-repo-host-0  pod delete operations performed 2-3 times. It was observed that the exec command inside monitor function ( under pgbackrest-config )  fails with the text file busy issue.

Can you please share steps if I can add some delays ( sleep ) in this container commands ?... I tried to do that on my cluster but the PGO resets any changes done when it restarts the pod... Also can you please point out to possible causes for this text file busy issue?

**Comment by getkedar1981** [comment] 2022-08-05 10:24
Can anyone please suggest if I can add delay/sleep in or before the monitor function for the pod postgres-repo-host-0 and container pgbackrest-config as the PGO cleans it up after pod restart.

**Comment by getkedar1981** [comment] 2022-08-10 11:44
> @getkedar1981 we are not seeing this issue in any of our various Kubernetes test environments.
> 
> Can you provide additional details about your specific Kubernetes environment? This issue currently appears to be environment specific.

Can anyone please suggest if I can add delay/sleep in or before the monitor function for the pod postgres-repo-host-0 and container pgbackrest-config as the PGO cleans it up after pod restart.

**Comment by benjaminjb** [comment] 2022-10-14 16:02
A couple of notes:

(1) In the future, if you need immediate support, please see the[ support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/) page.

(2) The postgres-operator dropped support for kubernetes 1.19 a while ago -- according to the history of the README in the postgres-operator repo, that change happened 7 months ago; and we dropped support for 1.20 a few months ago also. (But there may have been some time when that was 

(3) I have tried to replicate this in our currently supported environment, and no matter how many times I delete the *-repo-host-0, it comes back up without problem. Can you give more information about your environment?

**Comment by getkedar1981** [comment] 2022-10-17 03:56
Hi,

   I have tried on kubernetes 1.21 also and observed same result just for a single line of code as below. I think this has more to do with the underlying OS. In our case, its CentOS 7.6  ( Linux  3.10.0-957).
It looks like the below line from monitor function is has the issue - 

**~]$  exec {fd}<> <(:)
-bash: fd: Text file busy**

On which platform and OS you have tested this?... Any workaround you can suggest in this regard?....Is it possible to modify that monitor function script to use a regular ‘sleep 5’ instead of the round-about way of reading from a fd with a timeout of 5sec ?... if not, can you suggest any option for us to edit this on our cluster locally and have a persistent change for the pods under question on our cluster atleast?

**Comment by benjaminjb** [comment] 2022-10-17 14:27
I want to look into this a bit more, but just to make sure I have the outlines of the problem:

1) if a pod with this monitor function stops, it sometimes errors out with "Text file busy"
2) _sometimes_ (say after deleting the pod a few times) it comes back healthy

Is that accurate?

Also, this monitor function get used in a few pods -- the repo pod, pgbouncer pod, and the postgres pod all have containers focused on reloading if certain configs/files get changed. If you kill, say, a pgbouncer pod, does it give you the same errors?

**Comment by getkedar1981** [comment] 2022-10-17 14:56
_If a pod with this monitor function stops, it sometimes errors out with "Text file busy" . Sometimes (say after deleting the pod a few times) it comes back healthy.
Is that accurate?_

This happens most of the times. Because if we create a few instances of postgres on the kubernetes cluster in same / different namespaces, 
we start seeing this issue for new pods ( repo-host pod and pgbackrest-config container ) as well as if we restart existing repo-host pods. 

So far this has been observed with the pod repo-host.

**Comment by benjaminjb** [comment] 2022-10-18 19:57
Huh, interesting. Would you mind sharing your yaml for creating this cluster? I'm particularly interested in the `postgresclusters.spec.backups.pgbackrest.repos.volume.volumeClaimSpec`

**Comment by getkedar1981** [comment] 2022-10-19 04:43
Hi,

   Here is the snip from the spec file which you wanted to take a look at : 

postgres]$ cat postgres.yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo3
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.5-1
  postgresVersion: 14
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.40-1
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi
  monitoring:
    pgmonitor:
      exporter:
        image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.2.0-0

**Comment by getkedar1981** [comment] 2022-10-20 12:17
Any updates on this?

**Comment by andrewlecuyer** [comment] 2022-10-25 14:47
What version of Docker is being used on your nodes?  Similar issues have been reported in older versions of Docker, which have subsequently been addressed in more recent releases.  Here is one such example:

https://github.com/moby/moby/issues/9547

It also looks like you are running a very old version of CentOS 7, i.e. `3.10.0-957` was released in 2018.  Considering we aren't seeing this issue in any other environments, this appears to be specifically related to this older version of CentOS 7 (and possibly also due to an older version of Docker).  There should be no limitation with PGO itself and CentOS 7, though we can't account for bugs/issues/deficiencies/etc. that remain in unpatched CentOS 7 environments.

I therefore recommend applying the latest OS, Docker, etc. patches to your environment, and if you continue to have trouble please let us know.  Otherwise, we plan to close this issue as an issue specific to this one environment, rather than an issue with PGO itself.

**Comment by getkedar1981** [comment] 2022-10-26 09:37
Here are the docker version details -  

 docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-96.gitb2f74b2.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      b2f74b2/1.13.1
 Built:           Wed May  1 14:55:20 2019
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-96.gitb2f74b2.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      b2f74b2/1.13.1
 Built:           Wed May  1 14:55:20 2019
 OS/Arch:         linux/amd64
 Experimental:    false


 . However, if you could let us know if we could modify the monitor function for which we are hitting this issue, then it will be of great help in that case.

**Comment by getkedar1981** [comment] 2022-10-27 11:55
Any updates on this?

**Comment by andrewlecuyer** [comment] 2022-10-27 20:50
I see that you are running a very old version of Docker - v1.13.1 was released on 2017-02-08.  It therefore looks like you are missing countless updates/patches across your OS, Docker, etc. that are likely contributing to your issue.

And since we are unable to reproduce (since we do not test with much older, unpatched OS's and Docker), we cannot offer proper guidance for how to work around this in your environment.  I am therefore proceeding with closing this issue.

If you do update CentOS, Docker, etc. with the latest patches and still see this issue, please feel free to submit a new issue.

**Closed by andrewlecuyer** 2022-10-27 20:50 UTC
Labels: v5, triaged

**Comment by getkedar1981** [comment] 2022-10-28 04:04
Hi Andrew,

   Can you please confirm the CentOS version on which you have tested this and its supported officially where this issue wont be seen?
   
Thanks,
Kedar

**Comment by getkedar1981** [comment] 2022-10-28 10:22
> I see that you are running a very old version of Docker - v1.13.1 was released on 2017-02-08. It therefore looks like you are missing countless updates/patches across your OS, Docker, etc. that are likely contributing to your issue.
> 
> And since we are unable to reproduce (since we do not test with much older, unpatched OS's and Docker), we cannot offer proper guidance for how to work around this in your environment. I am therefore proceeding with closing this issue.
> 
> If you do update CentOS, Docker, etc. with the latest patches and still see this issue, please feel free to submit a new issue.

Hi Andrew,

Can you please confirm the CentOS version on which you have tested this and its supported officially where this issue wont be seen?.... If we are on CentOS 7.9, is that a supported OS?...That is the latest CentOS 7 version and is supported by CentOS.

Thanks,
Kedar
