### ISSUE TITLE
User as DB Owner

### ISSUE THREAD

**Issue by suikast42** [CrunchyData/postgres-operator#3266] opened 2022-06-22 07:59 UTC
When I create a new user with the CRD then the owner of the new creates database is always postgres.

![image](https://user-images.githubusercontent.com/5046525/174976058-f0ed3a8f-c96e-4dd5-9ab1-3093073fed35.png)

**Comment by andrewlecuyer** [comment] 2022-07-13 04:07
@suikast42 what you are seeing is intended/expected per the current design of PGO.

If you're having a specific issue with PGO (and more specifically the behavior you described), or if you would like to request an enhancement (e.g. to change this behavior), please provide the details request in either our [Feature Request](https://github.com/CrunchyData/postgres-operator/issues/new?assignees=&labels=&template=feature_request.md) or [Bug Report](https://github.com/CrunchyData/postgres-operator/issues/new?assignees=&labels=&template=bug_report.md) templates.

**Comment by benjaminjb** [comment] 2022-12-29 21:24
Closing as intended behavior, please reopen if you need to make a feature request for some different behavior (along with the use-case

**Closed by benjaminjb** 2022-12-29 21:24 UTC

**Comment by JJGadgets** [comment] 2023-11-14 00:33
Why would this be the intended behaviour? Currently I have to manually `psql` and run `ALTER DATABASE myapp OWNER TO myapp;` for every user and database combo, and I'd prefer if database owners could be declared within the CR itself, without giving the users additional privileges _and_ having to use and maintain my own init scripts.

**Comment by mikeywuu** [comment] 2023-11-19 15:55
I would also be interested in this one. Due to this, a coupled deployment of gitlab is not working without manually adjusting the owner.

**Comment by keppla** [comment] 2024-01-16 22:42
+1 for a way to automatically grant ownership.
i understand that the current behavior this isn't a bug, but it's at least inconvenient for all usecases i can come up with.
