### ISSUE TITLE
Is there a limit on number of watched namespaces

### ISSUE THREAD

**Issue by dadez** [CrunchyData/postgres-operator#1300] opened 2020-02-25 09:34 UTC
** Which example are you working with? **
creating clusters take a while, over 10 minutes

**What is the current behavior?**
Sample cluster creation
```
$ pgo -n mynamespace show workflow dc2744d1-8f25-4056-a182-dd6af4fc8d73
parameter           value
---------           -----
pg-cluster          mycluster
task completed      2020-02-25.08.54.05
task submitted      2020-02-25.08.39.10
workflowid          dc2744d1-8f25-4056-a182-dd6af4fc8d73
```
As you can see, it tooks around 15 minutes for create the cluster.
I'm not sure if this is related to the amount of watched namespaces, but we are currently watching 39 namespaces (68 pgclusters), in the future, we will watch hundreds of them. 
I'm not sure how well does pgo works in such a case, and even if we could horizontally scale, it would not help.

For me, it's not clear where the operator loose time creating this cluster, we didn't have such problems providing other kubernetes objects, like via helm charts.

**What is the expected behavior?**
The cluster creation should not take so long.

**Other information** (e.g. detailed explanation, related issues,  etc)

**Please tell us about your environment:**
* Operating System:
Suse CaasP
* Where is this running ( Local , Cloud Provider)
local
* Storage being used (NFS, Hostpath, Gluster, etc):
NFS
* Container Image Tag:
centos7-4.1.0

* PostgreSQL Version:
11.5

* Platform (Docker, Kubernetes, OpenShift):
Kubernetes

* Platform Version:
1.10.11

**Comment by jkatz** [comment] 2020-02-25 16:08
@dadez How frequently does this occur? Are there other things running in your environment?

Have you tried with 4.2?

**Comment by jkatz** [comment] 2020-02-25 16:16
Also noting that this is an old version of Kubernetes (1.10) -- we only support 1.11+ :smile:

**Comment by dadez** [comment] 2020-02-25 17:16
Hi @jkatz 
thanks for your feedback.

We are planing to upgrade to 4.2, but we are not ready yet.
For kubernetes, we will have to wait even more :( 
Yes, each customer get a namespace where he can order postgresql clusters and other services, like minio, rabbitmq, ...
Other services are provided with helm charts and we have no problem there.

Since Friday nobody can order a cluster (via pgo-osb, which timeout after 12 minutes). I'm not aware of any changes on the platform and maybe we added 2 watched namespaces on the operator.

Even deleting clusters via pgo-cli did not work, all pgclusters have been deleted, but some pods, secrets and pvc have remain after 3 hours. I had to delete them manually.

Could disabling the eventing help ?

**Comment by dadez** [comment] 2020-02-25 17:18
Hi @jkatz 
thanks for your feedback.

We are planing to upgrade to 4.2, but we are not ready yet.
For kubernetes, we will have to wait even more :( 
Yes, each customer get a namespace where he can order postgresql clusters and other services, like minio, rabbitmq, ...
Other services are provided with helm charts and we have no problem there.

Since Friday nobody can order a cluster (via pgo-osb, which timeout after 12 minutes). I'm not aware of any changes on the platform and maybe we added 2 watched namespaces on the operator.

Even deleting clusters via pgo-cli did not work, all pgclusters have been deleted, but some pods, secrets and pvc have remain after 3 hours. I had to delete them manually.

Could disabling the eventing help ?

**Comment by jkatz** [comment] 2020-02-25 23:31
@dadez That's no fun :( Thanks for the info. We'll take a look at it.

**Comment by dadez** [comment] 2020-02-26 09:31
@jkatz 
can you explain what is supposed to happend between this steps
09:05 I ran `pgo create cluster`
```
apiserver time="2020-02-26 09:05:38 +0000" level=debug msg="clusterservice.CreateClusterHandler called"
apiserver time="2020-02-26 09:05:38 +0000" level=error msg="secret mycluster-postgres-secret not found" 
apiserver time="2020-02-26 09:05:38 +0000" level=debug msg="created secret mycluster-postgres-secret" 
apiserver time="2020-02-26 09:05:38 +0000" level=debug msg="created secret mycluster-primaryuser-secret" 
apiserver time="2020-02-26 09:05:38 +0000" level=debug msg="created secret mycluster-testuser-secret" 
apiserver time="2020-02-26 09:05:38 +0000" level=error msg="secret mycluster-backrest-repo-config not found" 
apiserver time="2020-02-26 09:05:39 +0000" level=debug msg="created secret mycluster-backrest-repo-config" 
apiserver time="2020-02-26 09:05:39 +0000" level=debug msg="created pgtask mycluster-createcluster" 
```
first 5 mintues later, pgcluster is created
```
operator time="2020-02-26 09:08:12 +0000" level=debug msg="pgcluster added: mycluster" 
operator time="2020-02-26 09:08:59 +0000" level=debug msg="in createPVC" 
operator time="2020-02-26 09:10:24 +0000" level=info msg="creating Pgcluster object  in namespace mynamespace" 
```
then, 3 minutes later, backrest service is created
+1 minute pvc is created
+2 minutes collect secret is created
+2 minutes, deployment is created
```
operator time="2020-02-26 09:13:03 +0000" level=info msg="created service mycluster-backrest-shared-repo" 
operator time="2020-02-26 09:14:33 +0000" level=debug msg="created backrest-shared-repo pvc [mycluster-pgbr-repo]" 
operator time="2020-02-26 09:16:11 +0000" level=debug msg="created secret mycluster-collect-secret" 
operator time="2020-02-26 09:18:11 +0000" level=info msg="created deployment mycluster" 
```
Is there a way to figure out where the operator stucks between this steps ?

the workflow seems to never end up, I never get a task completed anymore

```
$ pgo -n mynamespace show workflow 6eb420a3-7c07-4b09-9f1c-e907c796cf83
parameter           value
---------           -----
pg-cluster          mycluster
task submitted      2020-02-26.09.05.39
workflowid          6eb420a3-7c07-4b09-9f1c-e907c796cf83
```

**Comment by jkatz** [comment] 2020-02-26 18:19
@dadez I will give you the nonanswer (but perhaps preferred answer) that we have reproduced the issue and have begun developing a solution :wink:

**Comment by dadez** [comment] 2020-02-26 18:34
@jkatz 
thank you for your help, 
if you have any workaround, please let me know

**Comment by dadez** [comment] 2020-02-27 11:05
@jkatz 
fyi, I have a workaround for now
We have reduced the watched namespaces to 25, now we can provision clusters again.

Beside telling the "new" watched namespace list on ansible update, I had to manually remove
- roles
- rolebindings
- service accounts
- labels

on all namespaces which I dont want to watch anymore.
Somehow, this namespaces are still seen from the operator.
We cannot delete namespace as other services runs beside postgresql.

**Comment by jkatz** [comment] 2020-02-27 14:01
@dadez Thanks for the info. We're working on ensuring you don't need that workaround, but that certainly helps with testing.

Thanks again for helping us to troubleshoot.

**Comment by jose-joye** [comment] 2020-03-05 10:18
@jkatz 
We have tested the same with pgo 4.2.2. We have the exact same issue (as reported for pgo 4.1.x).
You mentioned that you are working on a patch for this.
Any chance to get this prior 4.3 (so we can apply it on top of 4.2.2)?

In fact, on our side we are reaching the maximum ns limitation.

Thanks for any help
José

**Comment by jkatz** [comment] 2020-03-05 15:31
I can tell you we are actively working on a fix.

I don’t know if it will be backpatched until we review it.

It will not be available until the next release. We have no plans to make an emergency release around this.

**Comment by jose-joye** [comment] 2020-03-05 16:58
Any known date foreseen for the next release?

Thanks
José

**Comment by jkatz** [comment] 2020-03-05 17:06
We aim to release 4.3 before the end of the quarter. Since 4.1 ssh, we’re aiming for feature releases once a quarter.

**Comment by tvictor-optoro** [comment] 2020-03-20 04:19
Hi @jkatz, I'm glad to see you all are working on this issue as it's currently a problem for my organization that's only getting worse as we migrate more services onto kubernetes. Do you all have a workaround that can be implemented in the meantime while we wait for 4.3 to be released?

Also will 4.3 support the same postgres versions currently supported by 4.2.1?

**Comment by dadez** [comment] 2020-03-26 16:18
Hi @jkatz, you just published the version 4.3.0. Beta 1, kudos.
I didn't see any information about this problem. Do you know if it will be solved in 4.3.0 ?

thanks in advance

**Comment by jkatz** [comment] 2020-03-26 16:48
Hi,

We've been actively researching the issue since it was brought up and actively experimenting and working on the past several days. The heart of the problem is more complex than just "fixing the Operator" as we have noticed different behaviors in different environments:

- In a vanilla Kubernetes setup, we were unable to reproduce the issue. We had set up 80 namespaces and everything was fine.
- In a GKE environment, we hit the limit at ~35 namespaces.

Part of the issue stems from Kubernetes client restrictions (read QoS) that are put based upon the deployment environment. This can vary from environment to environment, so of course we want to account for those. The requests also did complete, albeit it would take an inordinate amount of time.

That being said, @andrewlecuyer has made some real progress on resolving the issue, which involves changes to the controllers that will ultimately address the namespace issue. Testing thus far has been positive, and we're confident that this will resolve the issue. Because this hits at the heart of the Operator, we want to ensure that we do it correctly, and our aim is to make it available in 4.3.0.

I truly understand this is an immediate issue and we're sorry that it's impacting you. Unfortunately, it has not been as simple as a fix in the Operator, but understanding how this impacts different deployment environments given the above described behavior.

In the interim, the risk mitigation steps are to have your administrator increase your Kubernetes client QoS values to something higher or to not use the multi-namespace feature.

Even with the fix, there will likely still be some ceiling of namespaces that you can have under the purview of the Operator, but we're hoping that it's on par with the limits of Kubernetes.

Lastly, we are acutely aware of this issue. As soon as we have a patch available, I will be sure to update this thread. This has been high up on our list for awhile, but being able to truly reproduce and find an acceptable solution has presented challenges.

I thank you for your patience.

**Comment by jkatz** [comment] 2020-03-27 20:28
@andrewlecuyer has posted a patch for this via #1374

**Comment by jkatz** [comment] 2020-03-29 19:31
This is now merged.

**Closed by jkatz** 2020-03-29 19:31 UTC

**Comment by dadez** [comment] 2020-03-29 19:37
Awesome, thank you very much

**Comment by optovic** [comment] 2020-04-09 15:55
@jkatz would you mind clarifying what you mean by:
> In the interim, the risk mitigation steps are to have your administrator increase your Kubernetes client QoS values
