### ISSUE TITLE
R

### ISSUE THREAD

**Issue by internetuser2008** [CrunchyData/postgres-operator#1683] opened 2020-07-01 21:48 UTC
**Describe the bug**
When storage is define the database pod fails with error 
Not sure if this is but may be related to setting with Rancher storage. When settin

**To Reproduce**
1. Set the storage in postgres-operator.yml
```
                  - name: STORAGE1_NAME
                    value: "hostpathstorage"
                  - name: STORAGE1_ACCESS_MODE
                    value: "ReadWriteMany"
                  - name: STORAGE1_SIZE
                    value: "1G"
                  - name: STORAGE1_TYPE
                    value: "dynamic"
                    # value: "create"
                  - name: STORAGE1_CLASS
                    value: "cinder-release"
```

**Expected behavior**

**Screenshots**

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local, Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:

**Additional context**

**Comment by jkatz** [comment] 2020-07-01 22:17
Seems to be a duplicate of #1684

**Closed by jkatz** 2020-07-01 22:17 UTC
