### ISSUE TITLE
pgo 4.2.2: Multiple primary created after Restore 

### ISSUE THREAD

**Issue by jose-joye** [CrunchyData/postgres-operator#1333] opened 2020-03-10 20:20 UTC
This issue was reported for a prior version. However, we have the exact same behavior with pgo 4.2.2
Previous issue: #999 

some days ago, we were playing with the restore mechanism on one of our clusters to validate the process.
All went fine and the restore was validated. Restore pgtasks and jobs were successful and kept at the end of the process.

This morning we had a  network issue (or something similar) within our k8s environment.
this end up with the following state for our cluster:
```
cluster : pg-adrian-spring-music-database-c8a15248 (crunchy-postgres-ha:centos7-11.7-4.2.2)
	pod : pg-adrian-spring-music-database-c8a15248-altx-585fb4f5b7-r9fzk (Running) on l820000002408a (2/2) (replica)
	pvc : pg-adrian-spring-music-database-c8a15248-altx
	pod : pg-adrian-spring-music-database-c8a15248-gfqn-75959bfb56-9rfq6 (Running) on l820000002409a (2/2) (primary)
	pvc : pg-adrian-spring-music-database-c8a15248-gfqn
	pod : pg-adrian-spring-music-database-c8a15248-iudv-799c88964b-2rb6b (Running) on l820000002410a (2/2) (primary)
	pvc : pg-adrian-spring-music-database-c8a15248-iudv
	pod : pg-adrian-spring-music-database-c8a15248-ochy-755c494775-z6lk7 (Running) on l820000002405a (2/2) (primary)
	pvc : pg-adrian-spring-music-database-c8a15248-ochy
	pod : pg-adrian-spring-music-database-c8a15248-rsza-68f665d85b-46czr (Running) on l820000002411a (1/2) (unknown)
	pvc : pg-adrian-spring-music-database-c8a15248-rsza
	pod : pg-adrian-spring-music-database-c8a15248-sljm-8b48997b8-587g9 (Running) on l820000002403a (2/2) (primary)
	pvc : pg-adrian-spring-music-database-c8a15248-sljm
	pod : pg-adrian-spring-music-database-c8a15248-zhox-6b554d4d67-bpsvp (Running) on l820000002407a (2/2) (primary)
	pvc : pg-adrian-spring-music-database-c8a15248-zhox
	resources : CPU Limit=1 Memory Limit=1Gi, CPU Request=0.25 Memory Request=256Mi
	storage : Primary=16Gi Replica=16Gi
	deployment : pg-adrian-spring-music-database-c8a15248-altx
	deployment : pg-adrian-spring-music-database-c8a15248-backrest-shared-repo
	deployment : pg-adrian-spring-music-database-c8a15248-gfqn
	deployment : pg-adrian-spring-music-database-c8a15248-iudv
	deployment : pg-adrian-spring-music-database-c8a15248-ochy
	deployment : pg-adrian-spring-music-database-c8a15248-rsza
	deployment : pg-adrian-spring-music-database-c8a15248-sljm
	deployment : pg-adrian-spring-music-database-c8a15248-zhox
	service : pg-adrian-spring-music-database-c8a15248 - ClusterIP (172.24.150.18)
	labels : crunchy-pgha-scope=pg-adrian-spring-music-database-c8a15248-gfqn crunchy_collect=true pgo-version=4.2.2 pgouser=admin storage-config=storage-8 current-primary=pg-adrian-spring-music-database-c8a15248-gfqn deployment-name=pg-adrian-spring-music-database-c8a15248-gfqn name=pg-adrian-spring-music-database-c8a15248 pg-pod-anti-affinity= workflowid=e34b3e22-97e9-45c9-a685-f5d288269fd2 autofail=false container-resources=single-starter-1 pg-cluster=pg-adrian-spring-music-database-c8a15248 archive-timeout=1800 crunchy-pgbadger=false pgo-backrest=true pgo-osb-instance=690d3ead-17f5-44b6-873c-1bf946a68ed3 service-type=ClusterIP 
```

Looking at the operator log we see the following (extract):
```
postgres-operator-65559b4448-gh7bg operator time="2020-03-10 09:54:16 +0000" level=debug msg="[JobController] onUpdate ns=cfae-bit-cbcd2 /apis/batch/v1/namespaces/cfae-bit-cbcd2/jobs/pg-adrian-spring-music-database-c8a15248-stanza-create active=0 succeeded=1 conditions=[[{Complete True 2020-03-05 12:13:58 +0000 UTC 2020-03-05 12:13:58 +0000 UTC  }]]" func="controller.(*JobController).onUpdate()" file="controller/jobcontroller.go:110" version=4.2.2
postgres-operator-65559b4448-gh7bg operator time="2020-03-10 09:54:16 +0000" level=debug msg="jobController onUpdate backrest stanza-create job case" func="controller.(*JobController).onUpdate()" file="controller/jobcontroller.go:333" version=4.2.2
postgres-operator-65559b4448-gh7bg operator time="2020-03-10 09:54:16 +0000" level=debug msg="backrest stanza successfully created for cluster pg-adrian-spring-music-database-c8a15248" func="controller.(*JobController).onUpdate()" file="controller/jobcontroller.go:335" version=4.2.2
postgres-operator-65559b4448-gh7bg operator time="2020-03-10 09:54:16 +0000" level=debug msg="proceeding with the initial full backup for cluster pg-adrian-spring-music-database-c8a15248 as needed for replica creation" func="controller.(*JobController).onUpdate()" file="controller/jobcontroller.go:336" version=4.2.2
postgres-operator-65559b4448-gh7bg operator time="2020-03-10 09:54:16 +0000" level=debug msg="the backrest repo pod for the initial backup of cluster pg-adrian-spring-music-database-c8a15248 is pg-adrian-spring-music-database-c8a15248-backrest-shared-rmprp7" func="controller.(*JobController).onUpdate()" file="controller/jobcontroller.go:344" version=4.2.2
```

--> it took an old job (successfully processed) and executed it without checking if the job was already processed

This can be shown in the jobController code (line 330)
```
// create an initial full backup for replica creation once stanza creation is complete
	if !isForegroundDeletion && labels[config.LABEL_BACKREST] == "true" &&
		labels[config.LABEL_BACKREST_COMMAND] == crv1.PgtaskBackrestStanzaCreate {
		log.Debugf("jobController onUpdate backrest stanza-create job case")
		if job.Status.Succeeded == 1 {
			log.Debugf("backrest stanza successfully created for cluster %s", labels[config.LABEL_PG_CLUSTER])
			log.Debugf("proceeding with the initial full backup for cluster %s as needed for replica creation",
				labels[config.LABEL_PG_CLUSTER])

			var backrestRepoPodName string
			for _, cont := range job.Spec.Template.Spec.Containers {
				for _, envVar := range cont.Env {
					if envVar.Name == "PODNAME" {
						backrestRepoPodName = envVar.Value
						log.Debugf("the backrest repo pod for the initial backup of cluster %s is %s",
							labels[config.LABEL_PG_CLUSTER], backrestRepoPodName)
					}
				}
			}
			backrestoperator.CreateInitialBackup(c.JobClient, job.ObjectMeta.Namespace,
				labels[config.LABEL_PG_CLUSTER], backrestRepoPodName)
		}
		return
	}
``` 

As a workaround, I guess we could delete the pgtasks and jobs related to the restore process (once completed). However, this sounds like a critical issue since having multiple masters makes the dB unusable without any notice.

José

**Comment by jkatz** [comment] 2020-03-10 21:23
Are they actually primaries, or are the labels just busted? What is the output of `kubectl logs` on the actual PostgreSQL pods?

**Comment by jose-joye** [comment] 2020-03-10 21:31
@jkatz : They are all happy leaders...

```
2020-03-10 19:17:56,318 INFO: Lock owner: pg-adrian-spring-music-database-c8a15248-gfqn-75959bfb56-9rfq6; I am pg-adrian-spring-music-database-c8a15248-gfqn-75959bfb56-9rfq6
2020-03-10 19:17:56,330 INFO: PAUSE: no action.  i am the leader with the lock

2020-03-10 19:18:33,052 INFO: Lock owner: pg-adrian-spring-music-database-c8a15248-ochy-755c494775-z6lk7; I am pg-adrian-spring-music-database-c8a15248-ochy-755c494775-z6lk7
2020-03-10 19:18:33,083 INFO: PAUSE: no action.  i am the leader with the lock

2020-03-10 19:19:21,907 INFO: Lock owner: pg-adrian-spring-music-database-c8a15248-sljm-8b48997b8-587g9; I am pg-adrian-spring-music-database-c8a15248-sljm-8b48997b8-587g9
2020-03-10 19:19:21,924 INFO: PAUSE: no action.  i am the leader with the lock

and so on
```

**Comment by jkatz** [comment] 2020-03-10 21:33
At least they're happy... :smile:

We'll look into it. This gives a big clue:

> it took an old job (successfully processed) and executed it without checking if the job was already processed

thanks!

**Comment by jose-joye** [comment] 2020-03-11 07:23
Thanks!

I was "naively" expecting that Patroni will prevent situation of having several concurrent Leader....
Am I wrong with this assumption?

**Comment by andrewlecuyer** [comment] 2020-03-11 14:17
@jose-joye one things that jumps out in the logs you provided is that the HA solution (Patroni) included within the PostgreSQL Operator, which is responsible for leader election, promoting a standby after a failure, etc. is currently paused and the cluster is therefore in maintenance mode.  This is indicated by `PAUSE` in the log output you provided, specifically where you see `INFO: PAUSE: no action.  i am the leader with the lock`.

Additionally, looking at your output from `pgo show cluster`, I can also see under the labels for the cluster that autofail is currently disabled (e.g. label `autofail=false`), which also indicates that the cluster is in maintenance mode.  The `autofail` label is the label that is specifically toggled when running the `pgo update cluster --disable-autofail` command, which pauses the HA solution and places the cluster into maintenance mode (and the opposite can be used to re-enabled autofail and disable maintenance mode, i.e. `pgo update cluster --enable-autofail`).

Therefore, was the server placed into maintenance mode (i.e. auto-failover disabled using the command shown above) at some point prior to the network outage?  

When in maintenance mode, which can be used in scenarios where database maintenance is needed and automatic failover needs to be temporarily disabled (e.g. since it might be necessary to start and stop databases as part of any needed maintenance), multiple masters are allowed.  This would therefore definitely explain why the Operator is currently allowing multiple masters for this cluster.  

And the solution here is to always ensure autofail is re-enabled using the `pgo update` command shown above (effectively disabling maintenance mode) to ensure the HA solution works as expected, and properly handles leader election (e.g. to ensure there is a single primary), automatic failovers, etc.

**Comment by jose-joye** [comment] 2020-03-11 15:21
@andrewlecuyer 
Thanks for the detail explanation!
For the autofail, if I'm correct, a pgo restore will automatically set the autofail to false.
We did not set it back to true after the restore process.

So, if I uderstand you correctly, having `autofail=false` will disable patroni and end up having possibly more than 1 leader/master. On the other end, having `autofail=true` will have prevented this.
---> If this is the case, patroni is just doing its job :-)

Now, related to the initial issue: the jobController should not consider again already completed and successful jobs. This may end up having unexpected results.

**Comment by jippeholwerda** [comment] 2020-04-01 09:29
I can confirm this is indeed still an issue with 4.2.2. I just did a restore on a cluster having a primary and one replica. After the restore, I noticed the replica was out of sync (wrong data). So I scaled down the cluster and removed the replica. After that operation, a previous restore job was rerun and now the cluster has two (also happy) primaries.

**Comment by yuanlinios** [comment] 2020-09-08 03:12
The same for 4.4.1.

Is there any way to workaround it? Even I ensure autofail=true after restore, and delete finished restore pgtask resources, these extra pods still appear. There is no network glitch in my cluster

This pgcluster is created as 1 primary + 1 replica
```
pgo show cluster hacluster -n proj-1

cluster : hacluster (crunchy-postgres-ha:centos7-12.4-4.4.1)
        pod : hacluster-atwk-666bf97dfc-g57dr (Running) on hdc-srv-06.int.vopsdev.com (0/1) (unknown)
                pvc: hacluster-atwk (954Mi)
        pod : hacluster-gbog-85cf6889f7-8r8fb (Running) on hdc-srv-07.int.vopsdev.com (0/1) (unknown)
                pvc: hacluster-gbog (954Mi)
        pod : hacluster-iqab-6b7c88cd67-77w7j (Running) on hdc-srv-05.int.vopsdev.com (1/1) (primary)
                pvc: hacluster-iqab (954Mi)
        pod : hacluster-nwpi-7bc8f667c4-d962v (Running) on hdc-srv-05.int.vopsdev.com (1/1) (replica)
                pvc: hacluster-nwpi (954Mi)
        resources : Memory: 128Mi
        deployment : hacluster-atwk
        deployment : hacluster-backrest-shared-repo
        deployment : hacluster-gbog
        deployment : hacluster-iqab
        deployment : hacluster-nwpi
        deployment : hacluster-pgbouncer
        service : hacluster - ClusterIP (172.16.8.34)
        service : hacluster-pgbouncer - ClusterIP (172.16.3.106)
        service : hacluster-replica - ClusterIP (172.16.8.198)
        pgreplica : hacluster-nwpi
        labels : crunchy_collect=false name=hacluster pgo-version=4.4.1 pgouser=pgoadmin workflowid=c53a4b28-f159-454b-affe-9c496da4d564 backrest-storage-type=s3 crunchy-pgha-scope=hacluster-gbog deployment-name=hacluster-gbog pg-cluster=hacluster pg-pod-anti-affinity= pgo-backrest=true autofail=true crunchy-pgbadger=false
```

logs from these extra postgresql pods
```
oc logs pod/hacluster-atwk-666bf97dfc-g57dr

2020-09-08 02:06:52,139 INFO: No PostgreSQL configuration items changed, nothing to reload.
2020-09-08 02:06:52,142 INFO: Lock owner: hacluster-atwk-666bf97dfc-2mx2w; I am hacluster-atwk-666bf97dfc-g57dr
2020-09-08 02:06:52,204 INFO: PAUSE: trying to bootstrap from leader 'hacluster-atwk-666bf97dfc-2mx2w'
2020-09-08 02:06:52,204 ERROR: failed to bootstrap from leader 'hacluster-atwk-666bf97dfc-2mx2w'
2020-09-08 02:06:52,204 INFO: Removing data directory: /pgdata/hacluster-atwk
2020-09-08 02:07:02,142 INFO: Lock owner: hacluster-atwk-666bf97dfc-2mx2w; I am hacluster-atwk-666bf97dfc-g57dr
2020-09-08 02:07:02,143 INFO: PAUSE: trying to bootstrap from leader 'hacluster-atwk-666bf97dfc-2mx2w'
2020-09-08 02:07:02,143 ERROR: failed to bootstrap from leader 'hacluster-atwk-666bf97dfc-2mx2w'
2020-09-08 02:07:02,143 INFO: Removing data directory: /pgdata/hacluster-atwk
2020-09-08 02:07:12,142 INFO: Lock owner: hacluster-atwk-666bf97dfc-2mx2w; I am hacluster-atwk-666bf97dfc-g57dr
2020-09-08 02:07:12,143 INFO: PAUSE: trying to bootstrap from leader 'hacluster-atwk-666bf97dfc-2mx2w'
2020-09-08 02:07:12,144 ERROR: failed to bootstrap from leader 'hacluster-atwk-666bf97dfc-2mx2w'
2020-09-08 02:07:12,144 INFO: Removing data directory: /pgdata/hacluster-atwk
2020-09-08 02:07:22,142 INFO: Lock owner: None; I am hacluster-atwk-666bf97dfc-g57dr
2020-09-08 02:07:22,142 INFO: PAUSE: waiting for leader to bootstrap
2020-09-08 02:07:32,142 INFO: Lock owner: None; I am hacluster-atwk-666bf97dfc-g57dr
2020-09-08 02:07:32,142 INFO: PAUSE: waiting for leader to bootstrap
```









{

**Comment by jkatz** [comment] 2020-09-08 15:32
Do the Pods appear when running `kubectl get pods`?

What do the log say on `hacluster-iqab-6b7c88cd67-77w7j`? According to the output, there seems to be a healthy primary and replica, and there are two replicas that may require manual intervention.

You may need to use `patronictl reinit` on the busted Pod as it could be in a state where the HA system cannot do anything else on it and requires manual intervention.

The HA solution will help with most cases, but based on the current state, environmental factors, etc., situations may require manual intervention. I'm describing "healing/recovery" here instead of [restore](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/disaster-recovery/), just to be clear.

Lastly, there has been significant work done on the "restore" functionality both in 4.4.0 ([`pgo create cluster --restore-from`](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/disaster-recovery/#restore-to-a-new-cluster)) and for the upcoming 4.5.0 release (CrunchyData/crunchy-containers#1272, #1801, #1843) which should resolve many of the reported issues with `pgo restore` and provide a cleaner recovery after the restore (e.g. retaining customizations).

**Comment by yuanlinios** [comment] 2020-09-09 03:12
Hello @jkatz 

Thanks for your reply!.

I wiped my original pgcluster, tried several times and found the result can be reproduced consistently (with 2 or 3 consecutive restore operations). Here is the detailed info.

The pgcluster is created as 1 primary + 1 replica
```
pgo show cluster hacluster -n proj-1

cluster : hacluster (crunchy-postgres-ha:centos7-12.4-4.4.1)
        pod : hacluster-fito-67fb48898f-mp299 (Running) on hdc-srv-05.int.vopsdev.com (1/1) (replica)
                pvc: hacluster-fito (954Mi)
        pod : hacluster-nxdi-57fdb698d4-ds2tf (Running) on hdc-srv-07.int.vopsdev.com (0/1) (unknown)
                pvc: hacluster-nxdi (954Mi)
        pod : hacluster-pjpm-857fbf5948-f4sqn (Running) on hdc-srv-06.int.vopsdev.com (1/1) (primary)
                pvc: hacluster-pjpm (954Mi)
        pod : hacluster-vibk-75bc4f4c9-xvszt (Running) on hdc-srv-06.int.vopsdev.com (0/1) (unknown)
                pvc: hacluster-vibk (954Mi)
        resources : Memory: 128Mi
        deployment : hacluster-backrest-shared-repo
        deployment : hacluster-fito
        deployment : hacluster-nxdi
        deployment : hacluster-pgbouncer
        deployment : hacluster-pjpm
        deployment : hacluster-vibk
        service : hacluster - ClusterIP (172.16.13.141)
        service : hacluster-pgbouncer - ClusterIP (172.16.12.115)
        service : hacluster-replica - ClusterIP (172.16.10.199)
        pgreplica : hacluster-fito
        labels : pgo-version=4.4.1 pgouser=pgoadmin autofail=true backrest-storage-type=s3 crunchy-pgha-scope=hacluster-nxdi name=hacluster pg-pod-anti-affinity= pgo-backrest=true crunchy-pgbadger=false crunchy_collect=false deployment-name=hacluster-nxdi pg-cluster=hacluster workflowid=42d50e46-1486-4ab3-a772-343f0a16c270
```
The label `crunchy-pgha-scope=hacluster-nxdi` and `deployment-name=hacluster-nxdi` do not look good to me. I assume the correct value should be `hacluster-pjpm`


Pod status
```
oc get pods

NAME                                              READY   STATUS      RESTARTS   AGE
backrest-backup-hacluster-tr6sk                   0/1     Completed   0          22h
hacluster-backrest-shared-repo-7456fdc9bc-c5nbc   1/1     Running     0          22h
hacluster-fito-67fb48898f-mp299                   1/1     Running     0          22h
hacluster-nxdi-57fdb698d4-ds2tf                   0/1     Running     0          19h
hacluster-pgbouncer-7794cf47b8-tqdj5              1/1     Running     0          22h
hacluster-pjpm-857fbf5948-f4sqn                   1/1     Running     0          22h
hacluster-stanza-create-rrtlb                     0/1     Completed   0          22h
hacluster-vibk-75bc4f4c9-xvszt                    0/1     Running     0          19h
restore-hacluster-axvv-9mgqv                      0/1     Completed   0          22h
restore-hacluster-bbmy-gm7sk                      0/1     Completed   0          22h
restore-hacluster-uhcf-r8t94                      0/1     Completed   0          22h
```
These "unknown" postgresql pods are running, but not ready.

Logs from primary pod
```
oc logs hacluster-pjpm-857fbf5948-f4sqn

2020-09-08 19:54:43,214 INFO: Lock owner: hacluster-pjpm-857fbf5948-f4sqn; I am hacluster-pjpm-857fbf5948-f4sqn
2020-09-08 19:54:43,307 INFO: no action.  i am the leader with the lock
2020-09-08 19:54:53,214 INFO: Lock owner: hacluster-pjpm-857fbf5948-f4sqn; I am hacluster-pjpm-857fbf5948-f4sqn
2020-09-08 19:54:53,308 INFO: no action.  i am the leader with the lock
2020-09-08 19:55:03,214 INFO: Lock owner: hacluster-pjpm-857fbf5948-f4sqn; I am hacluster-pjpm-857fbf5948-f4sqn
2020-09-08 19:55:03,307 INFO: no action.  i am the leader with the lock
2020-09-08 19:55:13,214 INFO: Lock owner: hacluster-pjpm-857fbf5948-f4sqn; I am hacluster-pjpm-857fbf5948-f4sqn
2020-09-08 19:55:13,308 INFO: no action.  i am the leader with the lock
```

Logs from replica pod
```
oc logs hacluster-fito-67fb48898f-mp299

2020-09-08 21:10:39,058 INFO: does not have lock
2020-09-08 21:10:39,059 INFO: no action.  i am a secondary and i am following a leader
2020-09-08 21:10:49,057 INFO: Lock owner: hacluster-pjpm-857fbf5948-f4sqn; I am hacluster-fito-67fb48898f-mp299
2020-09-08 21:10:49,058 INFO: does not have lock
2020-09-08 21:10:49,059 INFO: no action.  i am a secondary and i am following a leader
2020-09-08 21:10:59,057 INFO: Lock owner: hacluster-pjpm-857fbf5948-f4sqn; I am hacluster-fito-67fb48898f-mp299
2020-09-08 21:10:59,058 INFO: does not have lock
2020-09-08 21:10:59,059 INFO: no action.  i am a secondary and i am following a leader
2020-09-08 21:11:09,058 INFO: Lock owner: hacluster-pjpm-857fbf5948-f4sqn; I am hacluster-fito-67fb48898f-mp299
2020-09-08 21:11:09,058 INFO: does not have lock
```

Logs from 1st "unknown" pod
```
oc logs hacluster-nxdi-57fdb698d4-ds2tf

2020-09-09 00:57:34,502 INFO: Lock owner: None; I am hacluster-nxdi-57fdb698d4-ds2tf
2020-09-09 00:57:34,503 INFO: PAUSE: waiting for leader to bootstrap
2020-09-09 00:57:44,502 INFO: Lock owner: None; I am hacluster-nxdi-57fdb698d4-ds2tf
2020-09-09 00:57:44,502 INFO: PAUSE: waiting for leader to bootstrap
2020-09-09 00:57:54,502 INFO: Lock owner: None; I am hacluster-nxdi-57fdb698d4-ds2tf
2020-09-09 00:57:54,503 INFO: PAUSE: waiting for leader to bootstrap
2020-09-09 00:58:04,502 INFO: Lock owner: None; I am hacluster-nxdi-57fdb698d4-ds2tf
2020-09-09 00:58:04,502 INFO: PAUSE: waiting for leader to bootstrap
```

Logs from 2nd "unknown" pod
```
oc logs hacluster-vibk-75bc4f4c9-xvszt

2020-09-09 01:01:26,225 INFO: Lock owner: None; I am hacluster-vibk-75bc4f4c9-xvszt
2020-09-09 01:01:26,225 INFO: PAUSE: waiting for leader to bootstrap
2020-09-09 01:01:36,225 INFO: Lock owner: None; I am hacluster-vibk-75bc4f4c9-xvszt
2020-09-09 01:01:36,225 INFO: PAUSE: waiting for leader to bootstrap
2020-09-09 01:01:46,225 INFO: Lock owner: None; I am hacluster-vibk-75bc4f4c9-xvszt
2020-09-09 01:01:46,225 INFO: PAUSE: waiting for leader to bootstrap
2020-09-09 01:01:56,225 INFO: Lock owner: None; I am hacluster-vibk-75bc4f4c9-xvszt
2020-09-09 01:01:56,225 INFO: PAUSE: waiting for leader to bootstrap
```

Patroni status from primary pod
```
curl http://localhost:8009/patroni
{"state": "running", "postmaster_start_time": "2020-09-08 02:56:23.193 UTC", "role": "master", "server_version": 120004, "cluster_unlocked": false, "xlog": {"location": 285212672}, "timeline": 4, "replication": [{"usename": "primaryuser", "application_name": "hacluster-fito-67fb48898f-mp299", "client_addr": "10.9.6.168", "state": "streaming", "sync_state": "async", "sync_priority": 0}], "database_system_identifier": "6869939725944492201", "patroni": {"version": "1.6.5", "scope": "hacluster-pjpm"}}

curl http://localhost:8009/cluster
{"members": [{"name": "hacluster-fito-67fb48898f-mp299", "role": "replica", "state": "running", "api_url": "http://10.9.6.168:8009/patroni", "host": "10.9.6.168", "port": 5432, "timeline": 4, "lag": 0}, {"name": "hacluster-pjpm-857fbf5948-f4sqn", "role": "leader", "state": "running", "api_url": "http://10.9.4.165:8009/patroni", "host": "10.9.4.165", "port": 5432, "timeline": 4}]}
```

Patroni status from replica
```
curl http://localhost:8009/patroni
{"state": "running", "postmaster_start_time": "2020-09-08 03:04:17.028 UTC", "role": "replica", "server_version": 120004, "cluster_unlocked": false, "xlog": {"received_location": 285212672, "replayed_location": 285212672, "replayed_timestamp": null, "paused": false}, "timeline": 4, "database_system_identifier": "6869939725944492201", "patroni": {"version": "1.6.5", "scope": "hacluster-pjpm"}}

curl http://localhost:8009/cluster
{"members": [{"name": "hacluster-fito-67fb48898f-mp299", "role": "replica", "state": "running", "api_url": "http://10.9.6.168:8009/patroni", "host": "10.9.6.168", "port": 5432, "timeline": 4, "lag": 0}, {"name": "hacluster-pjpm-857fbf5948-f4sqn", "role": "leader", "state": "running", "api_url": "http://10.9.4.165:8009/patroni", "host": "10.9.4.165", "port": 5432, "timeline": 4}]}
```

Patroni status from 1st "unknown" pod
```
curl http://localhost:8009/patroni
{"state": "stopped", "role": "uninitialized", "patroni": {"version": "1.6.5", "scope": "hacluster-nxdi"}, "pause": true}

curl http://localhost:8009/cluster
{"members": [{"name": "hacluster-nxdi-57fdb698d4-ds2tf", "role": "replica", "state": "stopped", "api_url": "http://10.9.7.41:8009/patroni", "host": "10.9.7.41", "port": 5432, "lag": "unknown"}], "pause": true}
```

Patroni status from 2nd "unknown" pod
```
curl http://localhost:8009/patroni
{"state": "stopped", "role": "uninitialized", "patroni": {"version": "1.6.5", "scope": "hacluster-vibk"}, "pause": true}

curl http://localhost:8009/cluster
{"members": [{"name": "hacluster-vibk-75bc4f4c9-xvszt", "role": "replica", "state": "stopped", "api_url": "http://10.9.4.168:8009/patroni", "host": "10.9.4.168", "port": 5432, "lag": "unknown"}], "pause": true}
```

I am not quite sure how to run the "manual intervention" under this situation. When I run `patronictl reinit hacluster-nxdi` from the "unknown" pod `hacluster-nxdi-57fdb698d4-ds2tf`, it prompts

> \+ Cluster: hacluster-nxdi (6869939725944492201) -----+---------+----+-----------+
> |              Member             |    Host   | Role |  State  | TL | Lag in MB |
> +---------------------------------+-----------+------+---------+----+-----------+
> | hacluster-nxdi-57fdb698d4-ds2tf | 10.9.7.41 |      | stopped |    |   unknown |
> +---------------------------------+-----------+------+---------+----+-----------+
> Maintenance mode: on
> Which member do you want to reinitialize [hacluster-nxdi-57fdb698d4-ds2tf]? []:

I want to fix the pgcluster and eliminate these unexpected pods, instead of reinitializing them. Would you please give me some details?

**Comment by jkatz** [comment] 2020-09-09 15:31
Discussing with @andrewlecuyer, the root cause should be addressed in those three patches I referenced (CrunchyData/crunchy-containers#1272, #1801, #1843), which amongst many things, focuses on replicas not coming up post-restore. I would recommend upgrading to 4.5.0 when it is available.

With the replicas that are in an "unknown" state, they are detached from the DCS. The command that I recommend is used to attempt to reattach them to the DCS. If you want to eliminate them, try the [`pgo scaledown`](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_scaledown/) command:

`pgo scaledown hacluster --target=hacluster-nxdi`

If that does not work, you will need to inspect the pgreplica (and possibly pgcluster) CRD to see if a hacluster-nxdi entry still exists. If it does, you will have to remove that. You will then have to manually remove the hacluster-nxdi Deployment, Secrets, PVC.

Beyond that, I believe the original issue that #1333 raises is resolved by the PRs referenced above.

**Closed by jkatz** 2020-09-09 15:31 UTC
